from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

HIGHLIGHTS_RED = Button(area={'zh-cn': (689, 624, 708, 638)}, color={'zh-cn': (227, 123, 99)}, button={'zh-cn': (689, 624, 708, 638)}, file={'zh-cn': './assets/zh-cn/daemon/HIGHLIGHTS_RED.png'})
PLAY_HIGHLIGHTS = Button(area={'zh-cn': (467, 690, 518, 715)}, color={'zh-cn': (158, 222, 250)}, button={'zh-cn': (467, 690, 518, 715)}, file={'zh-cn': './assets/zh-cn/daemon/PLAY_HIGHLIGHTS.png'})
