<script setup lang="ts">
import { computed, defineAsyncComponent, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api } from './api/client'
import { JsonSocket } from './api/ws'
import AppSelect from './components/AppSelect.vue'
import EventCalendar from './components/EventCalendar.vue'
import MaintenanceBanner from './components/MaintenanceBanner.vue'
import FieldItemTable from './components/config/FieldItemTable.vue'
import FieldPathPicker from './components/config/FieldPathPicker.vue'
import FieldPriority from './components/config/FieldPriority.vue'

// ECharts is only needed by one read-only statistics field.  Loading it on
// demand keeps normal configuration and scheduler pages within the first-load
// budget defined by the UI plan.
const FieldInterception = defineAsyncComponent(() => import('./components/config/FieldInterception.vue'))

type Instance = { name: string; state: number; mod: string; current_task?: string; next_task?: string; remark?: string }
type Field = { key: string; widget: string; title: string; help: string; value: any; display: string; options: any[]; mode?: string; data_endpoint?: string; path_picker?: any; special_data?: any }
const route = useRoute()
const router = useRouter()
// Canonical brand icon; Windows-native uses (notification, window, Tauri
// build) go through nkas.ico instead, both regenerated by
// dev_tools/replace_project_icons.py.
const brandIcon = '/static/gui/icon/nkas.png'
const instances = ref<Instance[]>([])
const schema = ref<any>({ menus: [], tasks: {} })
const queue = ref<any>({ running: [], pending: [], waiting: [] })
// Entries carry a stable id so the v-for patch is append/remove-only instead
// of re-rendering every row on each incoming line, and a precomputed rank so
// the level filter does not re-run a regex over the whole buffer per line.
type LogEntry = { id: number; html: string; rank: number }
const logs = ref<LogEntry[]>([])
let logSeq = 0
// Retention is per level class so the scrollback length stays fixed: with
// the backend at DEBUG level a debug flood would otherwise push visible
// lines out of a shared raw buffer and shrink the scrollable range.  Debug
// lines and non-debug lines each keep the last LOG_CLASS_LIMIT entries, so
// every filter level renders a stable number of rows.
const LOG_CLASS_LIMIT = 400
const LOG_BUFFER_LIMIT = LOG_CLASS_LIMIT * 2
// Incremented on every batch so auto-scroll still triggers once the buffer
// length saturates at LOG_BUFFER_LIMIT.
const logTick = ref(0)
const LOG_LEVEL_PATTERN = /log-line lv-(debug|info|warn|err)/
const logBody = ref<HTMLElement>()
const autoScroll = ref(true)
const logLevel = ref('info')
const LOG_LEVEL_RANK: Record<string, number> = { debug: 0, info: 1, warn: 2, err: 3 }
const logLevelOptions = computed(() => [{ value: 'debug', label: t('调试') }, { value: 'info', label: t('信息') }, { value: 'warn', label: t('警告') }, { value: 'err', label: t('错误') }])
function pushLogs(payload: string | string[]) {
  // The replay arrives as one batched array; live lines arrive one at a time.
  for (const html of Array.isArray(payload) ? payload : [payload]) {
    const match = html.match(LOG_LEVEL_PATTERN)
    logs.value.push({ id: ++logSeq, html, rank: match ? LOG_LEVEL_RANK[match[1]] : -1 })
  }
  if (logs.value.length > LOG_BUFFER_LIMIT) {
    let debugCount = 0
    for (const entry of logs.value) if (entry.rank === 0) debugCount++
    // Evict the oldest entry of whichever class is over its limit.
    while (logs.value.length > LOG_BUFFER_LIMIT) {
      const evictDebug = debugCount > LOG_CLASS_LIMIT
      const index = logs.value.findIndex(entry => (entry.rank === 0) === evictDebug)
      if (index < 0) break
      logs.value.splice(index, 1)
      if (evictDebug) debugCount--
    }
  }
  logTick.value++
}
// Level rows carry the lv-* class rendered by the backend log template.
// Section dividers have no level and stay visible at every filter setting;
// traceback blocks share their error summary's rank and are filtered with it.
const visibleLogs = computed(() => {
  const threshold = LOG_LEVEL_RANK[logLevel.value] ?? 0
  return logs.value.filter(line => line.rank < 0 || line.rank >= threshold).slice(-LOG_CLASS_LIMIT)
})
const error = ref('')
const toasts = ref<{ id: number; text: string; kind: string; action?: { label: string; run: () => void } }[]>([])
let toastSeq = 0
// duration <= 0 keeps the toast until it is closed manually.
function notify(text: string, kind = 'ok', duration = 1600, action?: { label: string; run: () => void }) {
  const id = ++toastSeq
  toasts.value.push({ id, text, kind, action })
  if (duration > 0) setTimeout(() => closeToast(id), duration)
}
function closeToast(id: number) { toasts.value = toasts.value.filter(toast => toast.id !== id) }
// Errors are transient toasts, not a persistent topbar strip: every
// `error.value = ...` assignment flows through this watcher.
watch(error, value => { if (value) { notify(value, 'error', 10000); error.value = '' } })
const systemStatus = ref<any>({ version: '—', updater_state: 'idle', theme: 'light', language: 'zh-CN', home_page: 'overview' })
const updateInfo = ref<any>({})
const notices = ref<any[]>([])
const taskFilter = ref('')
const collapsed = ref<Record<string, boolean>>({})
const railCollapsed = ref<Record<string, boolean>>({})
const sidebarCollapsed = ref(false)
// 移动端抽屉导航：'' = 关闭，'sidebar' = 总导航抽屉，'rail' = 任务列表抽屉。
// 桌面端（>768px）此状态无效果，布局保持不变。
const mobileNav = ref<'sidebar' | 'rail' | ''>('')
const schemaReady = ref(false)
const importBusy = ref<Record<string, boolean>>({})
const notifyTestBusy = ref(false)
const backendDown = ref(false)
function isLegacyElectronLayout() { return window.parent !== window }
const legacyElectron = isLegacyElectronLayout()
// Custom titlebar for the Tauri desktop shell, which runs without native
// window decorations.  The same SPA also loads in plain browsers, where
// __TAURI_INTERNALS__ is absent and the bar stays hidden.
const isTauri = Boolean((window as any).__TAURI_INTERNALS__)
const isMaximized = ref(false)
function tauriWindow(): any { return (window as any).__TAURI__?.window?.getCurrentWindow?.() }
async function tbMinimize() { await tauriWindow()?.minimize() }
async function tbToggleMaximize() { const win = tauriWindow(); if (!win) return; await win.toggleMaximize(); isMaximized.value = await win.isMaximized() }
async function tbHide() { await tauriWindow()?.hide() }
async function tbClose() { await tauriWindow()?.close() }
async function syncMaximized() { const win = tauriWindow(); if (win) isMaximized.value = await win.isMaximized() }
// The topbar previously also carried data-tauri-drag-region; on the header's
// own empty areas that native region raced with this handler and started the
// OS drag loop twice, which made dragging intermittently fail. Dragging is
// now driven solely from this mousedown handler (the window buttons are
// excluded). preventDefault also stops text selection from stealing the drag.
let lastDragDownAt = 0
let lastDragDownX = 0
let lastDragDownY = 0
// Shared window-drag driver for the in-page titlebar surfaces (topbar and
// sidebar brand). exclude is a selector for interactive children that must
// keep their own clicks (window buttons, sidebar toggle). Double-click
// toggles maximize, mirroring native windows.
function onWindowDragAreaMouseDown(event: MouseEvent, exclude: string) {
  if (!isTauri || event.button !== 0 || (event.target as HTMLElement).closest(exclude)) return
  const now = Date.now()
  if (now - lastDragDownAt < 300
    && Math.abs(event.clientX - lastDragDownX) < 5
    && Math.abs(event.clientY - lastDragDownY) < 5) {
    lastDragDownAt = 0
    tbToggleMaximize()
    return
  }
  lastDragDownAt = now
  lastDragDownX = event.clientX
  lastDragDownY = event.clientY
  event.preventDefault()
  tauriWindow()?.startDragging()
}
function onTopbarMouseDown(event: MouseEvent) { onWindowDragAreaMouseDown(event, '.tb-btn') }
function onBrandMouseDown(event: MouseEvent) { onWindowDragAreaMouseDown(event, '.side-toggle') }
const staticLabels: Record<string, Record<string, string>> = {
  '总览': { 'en-US': 'Dashboard', 'ja-JP': 'ダッシュボード' }, '实例': { 'en-US': 'Instances', 'ja-JP': 'インスタンス' },
  '新建实例': { 'en-US': 'New instance', 'ja-JP': '新しいインスタンス' }, '系统': { 'en-US': 'System', 'ja-JP': 'システム' },
  '多开': { 'en-US': 'Multi-instance', 'ja-JP': 'マルチインスタンス' },
  '关于': { 'en-US': 'About', 'ja-JP': '情報' }, '主题': { 'en-US': 'Theme', 'ja-JP': 'テーマ' }, '任务总览': { 'en-US': 'Task overview', 'ja-JP': 'タスク概要' },
  '筛选任务…': { 'en-US': 'Filter tasks…', 'ja-JP': 'タスクを絞り込む…' }, '调度器': { 'en-US': 'Scheduler', 'ja-JP': 'スケジューラー' },
  '实时日志': { 'en-US': 'Live log', 'ja-JP': 'リアルタイムログ' },
  '自动滚动': { 'en-US': 'Auto-scroll', 'ja-JP': '自動スクロール' }, '当前任务': { 'en-US': 'Current task', 'ja-JP': '現在のタスク' }, '清空': { 'en-US': 'Clear', 'ja-JP': 'クリア' },
  '下一任务': { 'en-US': 'Next task', 'ja-JP': '次のタスク' }, '启动': { 'en-US': 'Start', 'ja-JP': '開始' }, '停止': { 'en-US': 'Stop', 'ja-JP': '停止' },
  '任务设置': { 'en-US': 'Task settings', 'ja-JP': 'タスク設定' }, '实例总数': { 'en-US': 'Instances', 'ja-JP': 'インスタンス数' },
  '运行中': { 'en-US': 'Running', 'ja-JP': '実行中' }, '空闲': { 'en-US': 'Idle', 'ja-JP': '待機中' }, '调度运行中': { 'en-US': 'Scheduler running', 'ja-JP': 'スケジューラー実行中' }, '已停止或异常': { 'en-US': 'Stopped or failed', 'ja-JP': '停止または異常' }, '正在导入…': { 'en-US': 'Importing…', 'ja-JP': 'インポート中…' },
  '无': { 'en-US': 'None', 'ja-JP': 'なし' }, '进入 →': { 'en-US': 'Open →', 'ja-JP': '開く →' }, '＋ 新建实例': { 'en-US': '＋ New instance', 'ja-JP': '＋ 新しいインスタンス' },
  '导入配置': { 'en-US': 'Import configuration', 'ja-JP': '設定をインポート' }, '名称': { 'en-US': 'Name', 'ja-JP': '名前' }, '状态': { 'en-US': 'Status', 'ja-JP': '状態' }, '操作': { 'en-US': 'Actions', 'ja-JP': '操作' },
  '导出': { 'en-US': 'Export', 'ja-JP': 'エクスポート' }, '删除': { 'en-US': 'Delete', 'ja-JP': '削除' }, '备注': { 'en-US': 'Remark', 'ja-JP': '備考' },
  '源码更新': { 'en-US': 'Source update', 'ja-JP': 'ソースコード更新' }, '当前版本': { 'en-US': 'Current version', 'ja-JP': '現在のバージョン' }, '更新': { 'en-US': 'Update', 'ja-JP': '更新' },
  '检查更新': { 'en-US': 'Check for updates', 'ja-JP': '更新を確認' }, '强制重启': { 'en-US': 'Restart now', 'ja-JP': '今すぐ再起動' }, '更新记录': { 'en-US': 'History', 'ja-JP': '更新履歴' },
  '检查中…': { 'en-US': 'Checking…', 'ja-JP': '確認中…' }, '更新中…': { 'en-US': 'Updating…', 'ja-JP': '更新中…' }, '更新失败': { 'en-US': 'Update failed', 'ja-JP': '更新失敗' }, '更新完成，正在刷新页面…': { 'en-US': 'Update finished, reloading…', 'ja-JP': '更新完了、再読み込み中…' }, '立即更新': { 'en-US': 'Update now', 'ja-JP': '今すぐ更新' }, '重试更新': { 'en-US': 'Retry update', 'ja-JP': '更新を再試行' }, '更新超时，请稍后手动刷新页面': { 'en-US': 'Update timed out, please reload later', 'ja-JP': '更新がタイムアウト、後で再読み込みしてください' },
  '有新版本可用': { 'en-US': 'Update available', 'ja-JP': '新しいバージョンあり' }, '已是最新': { 'en-US': 'Up to date', 'ja-JP': '最新です' }, '发现新版本，可在更新页更新': { 'en-US': 'New version found — see the update page', 'ja-JP': '新しいバージョンを検出、更新ページへ' }, '前往更新': { 'en-US': 'Go to update', 'ja-JP': '更新ページへ' },
  '启动器更新': { 'en-US': 'Launcher update', 'ja-JP': 'ランチャー更新' }, '此功能仅在1.x版本中可用': { 'en-US': 'Only available in version 1.x', 'ja-JP': 'バージョン1.xでのみ利用できます' },
  '更新nkas程序（exe）本身': { 'en-US': 'Updates the nkas program (exe) itself', 'ja-JP': 'nkasプログラム（exe）本体を更新します' },
  '启动器有新版本，可在更新页更新': { 'en-US': 'New launcher version available — see the update page', 'ja-JP': 'ランチャーの新しいバージョンがあります。更新ページへ' },
  '更新启动器将中断正在运行的任务并自动重启程序，确定继续？': { 'en-US': 'Updating the launcher interrupts running tasks and restarts the program. Continue?', 'ja-JP': 'ランチャーの更新は実行中のタスクを中断し、プログラムを自動再起動します。続行しますか？' },
  '更新完成，正在重启…': { 'en-US': 'Update finished, restarting…', 'ja-JP': '更新完了、再起動中…' },
  '重启中…': { 'en-US': 'Restarting…', 'ja-JP': '再起動中…' }, '后端正在重启，页面将自动刷新…': { 'en-US': 'Backend restarting, the page will reload…', 'ja-JP': 'バックエンド再起動中、ページを再読み込みします…' }, '重启超时，请手动刷新页面': { 'en-US': 'Restart timed out, please reload manually', 'ja-JP': '再起動がタイムアウト、手動で再読み込みしてください' },
  '立即运行': { 'en-US': 'Run now', 'ja-JP': '今すぐ実行' }, '本页分组': { 'en-US': 'Groups on this page', 'ja-JP': 'このページのグループ' },
  '队列中': { 'en-US': 'Queued', 'ja-JP': 'キュー中' }, '等待中': { 'en-US': 'Waiting', 'ja-JP': '待機中' },
  '暂无运行任务': { 'en-US': 'No running task', 'ja-JP': '実行中のタスクなし' }, '队列为空': { 'en-US': 'Queue is empty', 'ja-JP': 'キューは空です' },
  '未启用': { 'en-US': 'Disabled', 'ja-JP': '無効' }, '已启用': { 'en-US': 'Enabled', 'ja-JP': '有効' },
  '待机': { 'en-US': 'Standby', 'ja-JP': '待機' },
  '已保存': { 'en-US': 'Saved', 'ja-JP': '保存しました' },
  '知道了': { 'en-US': 'Got it', 'ja-JP': '了解' }, '系统通知': { 'en-US': 'System notice', 'ja-JP': 'システム通知' },
  '管理员权限不足': { 'en-US': 'Administrator privileges required', 'ja-JP': '管理者権限が必要です' },
  'PC 客户端需要脚本以管理员权限运行。请退出程序，右键启动程序或快捷方式，在「属性 → 兼容性」中勾选「以管理员身份运行此程序」，然后重新启动。': { 'en-US': 'The PC client requires the script to run with administrator privileges. Exit the program, right-click the launcher or shortcut, tick "Run this program as an administrator" under Properties → Compatibility, then start it again.', 'ja-JP': 'PCクライアントの利用には管理者権限が必要です。プログラムを終了し、起動プログラムまたはショートカットを右クリックして、「プロパティ → 互換性」で「管理者としてこのプログラムを実行する」にチェックを入れてから再起動してください。' },
  '公告中心': { 'en-US': 'Announcements', 'ja-JP': 'お知らせ' }, '暂无公告': { 'en-US': 'No announcements', 'ja-JP': 'お知らせはありません' }, '未读': { 'en-US': 'Unread', 'ja-JP': '未読' },
  '有新的系统通知。': { 'en-US': 'You have a new system notice.', 'ja-JP': '新しいシステム通知があります。' },
  '后端连接中断，正在等待恢复…': { 'en-US': 'Backend disconnected, waiting to reconnect…', 'ja-JP': 'バックエンド切断、再接続待ち…' },
  '导入失败': { 'en-US': 'Import failed', 'ja-JP': 'インポート失敗' },
  '取消': { 'en-US': 'Cancel', 'ja-JP': 'キャンセル' }, '确定': { 'en-US': 'OK', 'ja-JP': 'OK' },
  '最小化': { 'en-US': 'Minimize', 'ja-JP': '最小化' }, '最大化': { 'en-US': 'Maximize', 'ja-JP': '最大化' },
  '还原': { 'en-US': 'Restore', 'ja-JP': '元に戻す' }, '隐藏到托盘': { 'en-US': 'Hide to tray', 'ja-JP': 'トレイに隠す' }, '关闭': { 'en-US': 'Close', 'ja-JP': '閉じる' },
  '复制来源实例': { 'en-US': 'Copy settings from', 'ja-JP': 'コピー元インスタンス' },
  '此操作不可恢复。': { 'en-US': 'This cannot be undone.', 'ja-JP': '元に戻せません。' },
  '未知任务': { 'en-US': 'Unknown task', 'ja-JP': '不明なタスク' },
  '调试': { 'en-US': 'Debug', 'ja-JP': 'デバッグ' }, '信息': { 'en-US': 'Info', 'ja-JP': '情報' }, '警告': { 'en-US': 'Warning', 'ja-JP': '警告' }, '错误': { 'en-US': 'Error', 'ja-JP': 'エラー' },
  '添加': { 'en-US': 'Add', 'ja-JP': '追加' },
  '部署': { 'en-US': 'Deploy', 'ja-JP': 'デプロイ' }, '还原默认': { 'en-US': 'Reset to defaults', 'ja-JP': 'デフォルトに戻す' },
  '模板': { 'en-US': 'Template', 'ja-JP': 'テンプレート' }, '国际': { 'en-US': 'International', 'ja-JP': '国際' }, '大陆': { 'en-US': 'Mainland China', 'ja-JP': '中国本土' },
  'Docker国际': { 'en-US': 'Docker International', 'ja-JP': 'Docker 国際' }, 'Docker国内': { 'en-US': 'Docker Mainland China', 'ja-JP': 'Docker 中国本土' },
  '修改部署配置可能导致更新失败或程序无法启动，修改需要重启后生效，请谨慎操作。': { 'en-US': 'Changing deploy settings may break updates or prevent startup; changes apply only after a restart. Proceed with care.', 'ja-JP': 'デプロイ設定の変更は更新失敗や起動不能を招く可能性があります。変更は再起動後に有効になります。慎重に操作してください。' },
  '将全部部署配置还原为默认值？': { 'en-US': 'Reset all deploy settings to defaults?', 'ja-JP': 'すべてのデプロイ設定をデフォルトに戻しますか？' },
  '已还原为默认值': { 'en-US': 'Reset to defaults', 'ja-JP': 'デフォルトに戻しました' },
  '日志': { 'en-US': 'Logs', 'ja-JP': 'ログ' }, '类型': { 'en-US': 'Type', 'ja-JP': '種類' }, '级别': { 'en-US': 'Level', 'ja-JP': 'レベル' },
  '日期': { 'en-US': 'Date', 'ja-JP': '日付' }, '关键字': { 'en-US': 'Keyword', 'ja-JP': 'キーワード' },
  '搜索关键字…': { 'en-US': 'Search keyword…', 'ja-JP': 'キーワード検索…' }, '全部': { 'en-US': 'All', 'ja-JP': 'すべて' },
  '刷新': { 'en-US': 'Refresh', 'ja-JP': '再読み込み' }, '没有匹配的日志': { 'en-US': 'No matching logs', 'ja-JP': '一致するログがありません' },
  '详细信息': { 'en-US': 'Details', 'ja-JP': '詳細情報' },
  '查看 log 目录下的日志文件，支持按类型、级别、日期和关键字筛选。': { 'en-US': 'Browse the log files in the log directory by type, level, date and keyword.', 'ja-JP': 'log ディレクトリのログファイルを種類・レベル・日付・キーワードで絞り込みます。' },
  '测试通知': { 'en-US': 'Test notification', 'ja-JP': 'テスト通知' },
  '发送一条测试通知，验证当前通知设置是否生效。': { 'en-US': 'Send a test notification to verify the current notification settings.', 'ja-JP': 'テスト通知を送信して、現在の通知設定が有効かどうかを確認します。' },
  '发送中…': { 'en-US': 'Sending…', 'ja-JP': '送信中…' },
  '系统通知已发送': { 'en-US': 'System notification sent', 'ja-JP': 'システム通知を送信しました' },
  '系统通知发送失败': { 'en-US': 'Failed to send system notification', 'ja-JP': 'システム通知の送信に失敗しました' },
  'OnePush 推送成功': { 'en-US': 'OnePush push succeeded', 'ja-JP': 'OnePush プッシュ成功' },
  'OnePush 推送失败，请检查配置': { 'en-US': 'OnePush push failed, please check the configuration', 'ja-JP': 'OnePush プッシュ失敗、設定を確認してください' },
}

const languageOptions = [{ value: 'zh-CN', label: '简体中文' }, { value: 'en-US', label: 'English' }, { value: 'ja-JP', label: '日本語' }]
const selectedName = computed(() => String(route.params.name || ''))
const selectedPage = computed(() => String(route.params.page || ''))
const selectedTask = computed(() => String(route.params.task || ''))
const taskSchema = computed(() => schema.value.tasks[selectedTask.value])
const isDashboard = computed(() => route.path === '/')
const isManage = computed(() => route.path === '/manage')
const isSettings = computed(() => route.path === '/settings')
const isDeploy = computed(() => route.path === '/deploy')
const isLogs = computed(() => route.path === '/logs')
const isAbout = computed(() => route.path === '/about')
const isWorkspace = computed(() => Boolean(selectedName.value))
const selectedInstance = computed(() => instances.value.find(item => item.name === selectedName.value))
const runningCount = computed(() => instances.value.filter(item => item.state === 1).length)
const visibleMenus = computed(() => schema.value.menus.map((menu: any) => ({ ...menu, tasks: menu.tasks.filter((task: any) => !taskFilter.value || task.name.toLowerCase().includes(taskFilter.value.toLowerCase())) })).filter((menu: any) => menu.tasks.length))
let stateSocket: JsonSocket | undefined
let logSocket: JsonSocket | undefined
let queueSocket: JsonSocket | undefined
let healthTimer: number | undefined
// Names of the instance whose schema and per-instance sockets are currently
// loaded.  Switching tasks within one instance must not refetch the schema
// or rebuild the rail, so both are keyed by instance name.
let workspaceName = ''
let socketsName = ''

function taskEnabled(task: string) { return schema.value.tasks[task]?.groups?.some((group: any) => group.fields.some((field: Field) => field.key.endsWith('.Scheduler.Enable') && field.value)) }
function stateText(state?: number) { return state === 1 ? t('调度运行中') : state === 2 ? t('空闲') : t('已停止或异常') }
function stateClass(state?: number) { return state === 1 ? 'running' : 'idle' }
function initials(name: string) { return name.slice(0, 1).toUpperCase() }
function pageTitle() { return isDashboard.value ? t('总览') : isManage.value ? t('多开') : isSettings.value ? t('更新') : isDeploy.value ? t('部署') : isLogs.value ? t('日志') : isAbout.value ? t('关于') : selectedPage.value === 'overview' ? t('任务总览') : taskSchema.value?.name || selectedTask.value }
function allFields() { return Object.values(schema.value.tasks).flatMap((task: any) => task.groups.flatMap((group: any) => group.fields)) as Field[] }
function isWideField(field: Field) { return Boolean(field.path_picker) || ['item_table', 'interception_stone_charts', 'interception_stone_import', 'textarea', 'priority'].includes(field.widget) }
// Autosized textareas are capped: an unbounded value (e.g. the Hosts entries)
// would stretch its group card past the viewport, and on tool pages the view
// does not scroll, which pushed the log card out of reach.  Past the cap the
// textarea scrolls internally instead.
const TEXTAREA_MAX_HEIGHT = 400
function fitTextarea(el: HTMLTextAreaElement) { if (el.classList.contains('code-input')) { el.style.height = ''; return } el.style.height = 'auto'; el.style.height = `${Math.min(el.scrollHeight + 2, TEXTAREA_MAX_HEIGHT)}px` }
function resizeTextarea(event: Event) { fitTextarea(event.target as HTMLTextAreaElement) }
const vAutosize = { mounted: (el: HTMLTextAreaElement) => fitTextarea(el), updated: (el: HTMLTextAreaElement) => fitTextarea(el) }
function escapeHtml(source: string) { return source.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;') }
function highlightYaml(source: string) {
  return source.split('\n').map(line => {
    const escaped = escapeHtml(line)
    if (/^\s*#/.test(line)) return `<span class="tok-com">${escaped}</span>`
    const match = escaped.match(/^(\s*[\w.-]+)(\s*:)(.*)$/)
    if (!match) return escaped || ' '
    const value = match[3]
      .replace(/('[^']*'|"[^"]*")/g, '<span class="tok-str">$1</span>')
      .replace(/\b(\d[\d.]*)\b/g, '<span class="tok-num">$1</span>')
      .replace(/\b(true|false|null|~)\b/g, '<span class="tok-kw">$1</span>')
    return `<span class="tok-key">${match[1]}</span>${match[2]}${value}`
  }).join('\n')
}
const JSON_TOKEN_PATTERN = /"(?:\\.|[^"\\])*"|-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?|\b(?:true|false|null)\b/g
function highlightJson(source: string) {
  let output = ''
  let offset = 0
  for (const match of source.matchAll(JSON_TOKEN_PATTERN)) {
    const index = match.index ?? 0
    const token = match[0]
    output += escapeHtml(source.slice(offset, index))
    let tokenClass = 'tok-num'
    if (token.startsWith('"')) tokenClass = /^\s*:/.test(source.slice(index + token.length)) ? 'tok-key' : 'tok-str'
    else if (/^(true|false|null)$/.test(token)) tokenClass = 'tok-kw'
    output += `<span class="${tokenClass}">${escapeHtml(token)}</span>`
    offset = index + token.length
  }
  return output + escapeHtml(source.slice(offset))
}
function isStructuredTextarea(field: Field) { return field.mode === 'yaml' || field.mode === 'json' }
function highlightTextarea(field: Field) {
  const source = String(field.value ?? '')
  return field.mode === 'json' ? highlightJson(source) : highlightYaml(source)
}
function groupId(group: any) { return `group-${group.key}` }
const activeGroup = ref('')
function onViewScroll(event: Event) {
  const groups = taskSchema.value?.groups || []
  if (!groups.length) return
  let current = groups[0].key
  for (const group of groups) {
    const el = document.getElementById(groupId(group))
    if (el && el.getBoundingClientRect().top <= 140) current = group.key
  }
  activeGroup.value = current
}
function jumpToGroup(group: any) { activeGroup.value = group.key; document.getElementById(groupId(group))?.scrollIntoView({ behavior: 'smooth', block: 'start' }) }
function t(source: string) { return systemStatus.value.language === 'zh-CN' ? source : staticLabels[source]?.[systemStatus.value.language] || source }
function formatTime(value: string) { const m = String(value || '').match(/^(\d{4})-(\d{2})-(\d{2})\s+(\d{2}:\d{2})/); return m ? `${m[2]}-${m[3]} ${m[4]}` : value }
function dayOf(value: string) { return String(value || '').slice(0, 10) }
function formatDate(value: string) { const m = String(value || '').match(/^(\d{4})-(\d{2})-(\d{2})/); return m ? `${m[2]}-${m[3]}` : value }

async function loadInstances() {
  try { instances.value = await api.get('/api/instances') } catch (exception: any) { error.value = exception.message }
}
async function loadSystem() {
  try {
    systemStatus.value = await api.get('/api/system/status')
    updateInfo.value = await api.get('/api/system/update')
    const noticeData = await api.get('/api/system/notices')
    notices.value = noticeData.notices || []
    announcements.value = noticeData.announcements || []
    // Unread announcements auto-open the center once per session; reconnect
    // reloads of loadSystem must not pop it again.
    if (!announcementAutoShown && announcements.value.some(item => !item.read)) {
      announcementAutoShown = true
      openAnnouncementCenter()
    }
    // Only a valid backend theme may override the local choice: right after
    // an update/reload the status payload can arrive without a usable theme,
    // and falling back to "light" here used to clobber both the page and the
    // stored preference.
    const theme = systemStatus.value.theme
    if (theme === 'dark' || theme === 'light') {
      document.documentElement.dataset.theme = theme
      localStorage.setItem('nkas-theme', theme)
    }
  } catch (exception: any) { error.value = exception.message }
}
async function refreshSpecial(field: Field) { if (field.data_endpoint && field.widget !== 'interception_stone_import') field.special_data = await api.get(field.data_endpoint) }
async function loadWorkspace() {
  if (!selectedName.value) return
  schemaReady.value = false
  try {
    schema.value = await api.get(`/api/${selectedName.value}/schema`)
    const monitors = await api.get('/api/system/monitors').catch(() => [])
    allFields().forEach(field => { if (field.key.endsWith('.ScreenNumber')) field.options = monitors })
    collapsed.value = {}
    Object.values(schema.value.tasks).forEach((task: any) => task.groups.forEach((group: any) => { if (group.collapsed) collapsed.value[group.key] = true }))
    // Rail groups start collapsed; in-app navigation keeps them untouched
    // because loadWorkspace only runs on an instance switch.
    railCollapsed.value = {}
    schema.value.menus.forEach((menu: any) => { railCollapsed.value[menu.key] = true })
    await Promise.all(allFields().filter(field => field.data_endpoint && field.widget !== 'interception_stone_import').map(field => refreshSpecial(field).catch(() => null)))
    queue.value = await api.get(`/api/${selectedName.value}/queue`)
    schemaReady.value = true
    workspaceName = selectedName.value
    activeGroup.value = taskSchema.value?.groups?.[0]?.key || ''
    error.value = ''
  } catch (exception: any) { error.value = exception.message }
}
function dashboard() { mobileNav.value = ''; router.push('/') }
function calendarError(message: string) { error.value = message }
function enter(name: string) { mobileNav.value = ''; router.push(`/i/${name}/overview`) }
function openTask(task: any, page: string) { mobileNav.value = ''; router.push(`/i/${selectedName.value}/${page}/${task.key}`) }
function openQueueItem(item: any) {
  const menu = schema.value.menus.find((item2: any) => item2.tasks.some((task: any) => task.key === item.command))
  router.push(`/i/${selectedName.value}/${menu?.page === 'tool' ? 'tool' : 'task'}/${item.command}`)
}
function toggleRail(menu: any) { railCollapsed.value[menu.key] = !railCollapsed.value[menu.key] }
async function lifecycle(action: 'start' | 'stop', name = selectedName.value) {
  try { await api.post(`/api/${name}/${action}`); await loadInstances() } catch (exception: any) {
    if (action === 'start' && exception?.code === 'admin_required') {
      openAlertModal(t('管理员权限不足'), t('PC 客户端需要脚本以管理员权限运行。请退出程序，右键启动程序或快捷方式，在「属性 → 兼容性」中勾选「以管理员身份运行此程序」，然后重新启动。'))
      return
    }
    error.value = exception.message
  }
}
async function saveValue(field: Field, value: any) {
  try {
    const result = await api.patch(`/api/${selectedName.value}/config`, { key: field.key, value })
    if (!result.ok) throw new Error(result.message)
    field.value = result.applied[field.key]
    notify(t('已保存'))
  } catch (exception: any) {
    error.value = exception.message
    throw exception
  }
}
function save(field: Field, event: Event) {
  const input = event.target as HTMLInputElement
  const value = field.widget === 'checkbox' ? input.checked : input.value
  // Roll the control back to the last persisted value when the save fails.
  saveValue(field, value).catch(() => {
    if (field.widget === 'checkbox') input.checked = Boolean(field.value)
    else input.value = field.value ?? ''
  })
}
// datetime-local only renders the "T" separator; stored values may use a
// space ("1989-12-27 00:00:00"), which would otherwise render as an empty
// picker.  Normalize for display only; seconds are dropped as the control
// does not edit them.
function datetimeValue(value: any) { return String(value ?? '').replace(' ', 'T').slice(0, 16) }
const DATETIME_SAVE_DELAY = 1000
const datetimeSaveTimers = new Map<string, number>()
function cancelDatetimeSave(field: Field) {
  const timer = datetimeSaveTimers.get(field.key)
  if (timer !== undefined) window.clearTimeout(timer)
  datetimeSaveTimers.delete(field.key)
}
function commitDatetime(field: Field, input: HTMLInputElement) {
  cancelDatetimeSave(field)
  // Native datetime inputs report an incomplete value as empty. Do not write
  // the stored value back while the user is moving between date/time parts.
  if (!input.value || input.value === datetimeValue(field.value)) return
  saveValue(field, input.value).catch(() => { input.value = datetimeValue(field.value) })
}
function scheduleDatetimeSave(field: Field, event: Event) {
  const input = event.target as HTMLInputElement
  cancelDatetimeSave(field)
  if (!input.value) return
  datetimeSaveTimers.set(field.key, window.setTimeout(() => commitDatetime(field, input), DATETIME_SAVE_DELAY))
}
function flushDatetimeSave(field: Field, event: Event) {
  const input = event.target as HTMLInputElement
  if (!input.value) {
    cancelDatetimeSave(field)
    input.value = datetimeValue(field.value)
    return
  }
  commitDatetime(field, input)
}
// Clearing saves immediately so the backend restores the default.
function clearField(field: Field) {
  cancelDatetimeSave(field)
  saveValue(field, '').catch(() => {})
}
async function pickedPath(field: Field, path: string) {
  try { await saveValue(field, path) } catch { return }
  if (field.path_picker?.after_select !== 'autofill_game_path_from_launcher') return
  const gamePath = allFields().find(item => item.key === 'PCClient.PCClientInfo.GamePath')
  if (gamePath && !gamePath.value) {
    const separator = path.includes('\\') ? '\\' : '/'
    await saveValue(gamePath, `${path.replace(/[\\/][^\\/]+$/, '')}${separator}..${separator}NIKKE${separator}game${separator}nikke.exe`).catch(() => null)
  }
}
async function importInterception(field: Field, path: string) {
  if (!field.data_endpoint) return
  importBusy.value[field.key] = true
  try { const result = await api.post(field.data_endpoint, { path }); if (!result.ok) throw new Error(result.message || t('导入失败')); const chart = allFields().find(item => item.widget === 'interception_stone_charts'); if (chart) await refreshSpecial(chart); notify(`已导入 ${result.imported || 0} 条，跳过 ${result.skipped || 0} 条。`, 'ok', 3000) } catch (exception: any) { error.value = exception.message } finally { delete importBusy.value[field.key] }
}
async function testNotify() {
  if (notifyTestBusy.value) return
  notifyTestBusy.value = true
  try {
    const result = await api.post(`/api/${selectedName.value}/notify/test`)
    const parts: string[] = []
    if (result.windows === true) parts.push(t('系统通知已发送'))
    if (result.windows === false) parts.push(t('系统通知发送失败'))
    if (result.onepush === true) parts.push(t('OnePush 推送成功'))
    if (result.onepush === false) parts.push(t('OnePush 推送失败，请检查配置'))
    notify(parts.join('；'), result.ok ? 'ok' : 'error', 4000)
  } catch (exception: any) { error.value = exception.message } finally { notifyTestBusy.value = false }
}
function toggleTheme() { const theme = document.documentElement.dataset.theme === 'light' ? 'dark' : 'light'; document.documentElement.dataset.theme = theme; localStorage.setItem('nkas-theme', theme); api.post('/api/system/theme', { theme }).then(() => systemStatus.value.theme = theme).catch(exception => error.value = exception.message) }
async function setLanguage(language: string) { try { await api.post('/api/system/language', { language }); await loadSystem(); await loadWorkspace() } catch (exception: any) { error.value = exception.message } }
// Deploy page: schema-driven editor over config/deploy.yaml.  The backend
// parses groups and per-field comments from deploy/template; edits save per
// field like task settings, and the page carries a warning plus a reset.
const deployGroups = ref<any[]>([])
async function loadDeploy() { try { deployGroups.value = (await api.get('/api/system/deploy')).groups } catch (exception: any) { error.value = exception.message } }
async function saveDeployValue(field: any, value: any) {
  try {
    const result = await api.patch('/api/system/deploy', { key: field.key, value })
    field.value = result.value
    notify(t('已保存'))
    if (field.key === 'Theme') { document.documentElement.dataset.theme = result.value; localStorage.setItem('nkas-theme', result.value); systemStatus.value.theme = result.value }
    if (field.key === 'HomePage') systemStatus.value.home_page = result.value
    if (field.key === 'Language') await setLanguage(result.value)
  } catch (exception: any) { error.value = exception.message }
}
function saveDeployField(field: any, event: Event) {
  const el = event.target as HTMLInputElement
  // 数字框清空时传 null，由后端恢复模板默认值
  saveDeployValue(field, field.widget === 'checkbox' ? el.checked : field.widget === 'number' ? (el.value === '' ? null : Number(el.value)) : el.value)
}
function toggleDeployMulti(field: any, value: string) {
  const current = Array.isArray(field.value) ? [...field.value] : []
  const index = current.indexOf(value)
  if (index >= 0) current.splice(index, 1)
  else current.push(value)
  saveDeployValue(field, current)
}
// Logs page: filtered viewer over the ./log/<date>_<source>.txt files.  The
// backend folds continuation lines (tracebacks) into the record opened by
// the last levelled line and returns the newest matching records; the level
// select reuses the live log's debug/info/warn/err threshold options.
type LogFileRef = { date: string; source: string }
const logFiles = ref<LogFileRef[]>([])
const logsDate = ref('')
const logsSource = ref('')
const logsLevel = ref('info')
const logsKeyword = ref('')
const logsRecords = ref<any[]>([])
const logsMatched = ref(0)
const logsTruncated = ref(false)
const logsLoading = ref(false)
const logsBody = ref<HTMLElement>()
const logsDateOptions = computed(() => [...new Set(logFiles.value.map(file => file.date))].map(date => ({ value: date, label: date })))
const logsSourceOptions = computed(() => [{ value: '', label: t('全部') }, ...[...new Set(logFiles.value.filter(file => file.date === logsDate.value).map(file => file.source))].map(source => ({ value: source, label: source }))])
const LOGS_RANK_CLASS = ['lv-debug', 'lv-info', 'lv-warn', 'lv-err']
function logsRankClass(rank: number) { return LOGS_RANK_CLASS[rank] || 'lv-info' }
function logsCountText() {
  const shown = logsRecords.value.length
  if (systemStatus.value.language === 'en-US') return logsTruncated.value ? `Matched ${logsMatched.value}, showing the latest ${shown}` : `${logsMatched.value} entries`
  if (systemStatus.value.language === 'ja-JP') return logsTruncated.value ? `${logsMatched.value} 件一致、最新 ${shown} 件を表示` : `${logsMatched.value} 件`
  return logsTruncated.value ? `共匹配 ${logsMatched.value} 条，仅显示最近 ${shown} 条` : `共 ${logsMatched.value} 条`
}
// Default the type filter to the first instance that logged on the selected
// date rather than the merged 全部 view; only re-pick when the current source
// has no file for the date.  全部 stays selectable once initialized.
let logsSourceInitialized = false
async function loadLogFiles() {
  try {
    logFiles.value = (await api.get('/api/system/logs/files')).files || []
    if (!logsDate.value || !logFiles.value.some(file => file.date === logsDate.value)) logsDate.value = logFiles.value[0]?.date || ''
    const sources = new Set(logFiles.value.filter(file => file.date === logsDate.value).map(file => file.source))
    if (!logsSourceInitialized || (logsSource.value !== '' && !sources.has(logsSource.value))) {
      logsSource.value = instances.value.find(item => sources.has(item.name))?.name || [...sources][0] || ''
      logsSourceInitialized = true
    }
  } catch (exception: any) { error.value = exception.message }
}
// A stale response must not overwrite a newer query: rapid keyword typing or
// the loadLogFiles date watch can fire several queries at once.
let logsQuerySeq = 0
async function queryLogs() {
  if (!isLogs.value) return
  const seq = ++logsQuerySeq
  if (!logsDate.value) { logsRecords.value = []; logsMatched.value = 0; logsTruncated.value = false; return }
  logsLoading.value = true
  try {
    const params = new URLSearchParams({ date: logsDate.value, source: logsSource.value, level: logsLevel.value, keyword: logsKeyword.value })
    const result = await api.get(`/api/system/logs?${params}`)
    if (seq !== logsQuerySeq) return
    logsRecords.value = result.records || []
    logsMatched.value = result.matched || 0
    logsTruncated.value = Boolean(result.truncated)
    await nextTick()
    if (logsBody.value) logsBody.value.scrollTop = logsBody.value.scrollHeight
  } catch (exception: any) { error.value = exception.message } finally { if (seq === logsQuerySeq) logsLoading.value = false }
}
async function refreshLogs() { await loadLogFiles(); await queryLogs() }
let logsKeywordTimer = 0
watch([logsDate, logsSource, logsLevel], queryLogs)
watch(logsKeyword, () => { window.clearTimeout(logsKeywordTimer); logsKeywordTimer = window.setTimeout(queryLogs, 400) })
const modal = ref<{ type: '' | 'create' | 'delete' | 'resetDeploy' | 'confirm' | 'alert'; name: string; origin: string; template: string; busy: boolean }>({ type: '', name: '', origin: 'template-nkas', template: 'intl', busy: false })
const originOptions = computed(() => ['template-nkas', ...instances.value.map(item => item.name)])
const deployTemplateOptions = computed(() => [{ value: 'intl', label: t('国际') }, { value: 'cn', label: t('大陆') }, { value: 'docker-intl', label: t('Docker国际') }, { value: 'docker-cn', label: t('Docker国内') }])
// Pre-fill the create form with the first free nkas-style name (nkas, nkas2,
// nkas3…) so the modal needs no placeholder hint.
function defaultInstanceName() {
  const names = new Set(instances.value.map(item => item.name))
  if (!names.has('nkas')) return 'nkas'
  let index = 2
  while (names.has(`nkas${index}`)) index++
  return `nkas${index}`
}
function openCreateModal() { modal.value = { type: 'create', name: defaultInstanceName(), origin: instances.value[0]?.name || 'template-nkas', template: 'intl', busy: false } }
function openDeleteModal(name: string) { modal.value = { type: 'delete', name, origin: '', template: '', busy: false } }
function openResetDeployModal() { modal.value = { type: 'resetDeploy', name: '', origin: '', template: 'intl', busy: false } }
// Generic confirmation so every risky action shares the same modal instead of
// mixing native confirm() with custom cards.
const modalConfirmMessage = ref('')
let modalConfirmAction: (() => void | Promise<void>) | null = null
function openConfirmModal(message: string, action: () => void | Promise<void>) {
  modalConfirmMessage.value = message
  modalConfirmAction = action
  modal.value = { type: 'confirm', name: '', origin: '', template: '', busy: false }
}
// Information-only popup (no follow-up action), e.g. the administrator
// privilege warning shown when a PC-client instance cannot start.
const modalAlertTitle = ref('')
const modalAlertMessage = ref('')
function openAlertModal(title: string, message: string) {
  modalAlertTitle.value = title
  modalAlertMessage.value = message
  modal.value = { type: 'alert', name: '', origin: '', template: '', busy: false }
}
async function confirmModal() {
  const m = modal.value
  if (m.busy) return
  if (m.type === 'alert') { m.type = ''; return }
  m.busy = true
  try {
    if (m.type === 'create') {
      const name = m.name.trim()
      if (!name) return
      await api.post('/api/instances', { name, origin: m.origin })
    } else if (m.type === 'delete') {
      await api.del(`/api/${m.name}`)
      if (selectedName.value === m.name) dashboard()
    } else if (m.type === 'confirm') {
      const action = modalConfirmAction
      modalConfirmAction = null
      m.type = ''
      await action?.()
      return
    } else if (m.type === 'resetDeploy') {
      // Theme/language revert to template defaults too; sync the cached theme
      // before reloading so the page restarts on the reverted palette.
      const result = await api.post('/api/system/deploy/reset', { template: m.template })
      localStorage.setItem('nkas-theme', result.theme)
      m.type = ''
      notify(t('已还原为默认值'))
      setTimeout(() => window.location.reload(), 600)
      return
    }
    m.type = ''
    await loadInstances()
  } catch (exception: any) { error.value = exception.message } finally { m.busy = false }
}
const updateChecking = ref(false)
// The update state changes behind the page's back (startup check, scheduled
// daily check), so refresh it whenever the update view is opened and keep
// polling while a check runs instead of showing a stale 检查中 forever.
let updatePollTimer = 0
async function refreshUpdateInfo() {
  window.clearTimeout(updatePollTimer)
  try { updateInfo.value = await api.get('/api/system/update') } catch { return }
  if (isSettings.value && updateInfo.value.state === 'checking') updatePollTimer = window.setTimeout(refreshUpdateInfo, 3000)
}
// Desktop launcher (nkas.exe) self-update: the Tauri shell exposes the
// updater through its own commands instead of the backend API, so this flow
// mirrors the source update card but drives window.__TAURI__.core.invoke.
// In plain browsers the bridge is absent and the card stays disabled.
const desktopInvoke = (): any => (window as any).__TAURI__?.core?.invoke
const isDesktopShell = Boolean(desktopInvoke())
const desktopUpdate = ref<any>(null)
const desktopChecking = ref(false)
const desktopApplying = ref(false)
let desktopUpdatePollTimer = 0
async function refreshDesktopUpdate() {
  window.clearTimeout(desktopUpdatePollTimer)
  if (!isDesktopShell) return
  try { desktopUpdate.value = await desktopInvoke()('desktop_update_status') } catch { return }
  if (isSettings.value && desktopUpdate.value?.checking) desktopUpdatePollTimer = window.setTimeout(refreshDesktopUpdate, 3000)
}
async function checkDesktopUpdate() {
  if (desktopChecking.value || !isDesktopShell) return
  desktopChecking.value = true
  try {
    desktopUpdate.value = await desktopInvoke()('desktop_update_check')
    // Poll until the background check finishes so the button can switch to
    // the update action when a new version shows up.
    for (let round = 0; round < 30; round++) {
      await new Promise(resolve => setTimeout(resolve, 2000))
      desktopUpdate.value = await desktopInvoke()('desktop_update_status')
      if (!desktopUpdate.value?.checking) break
    }
  } catch (exception: any) { error.value = String(exception?.message || exception) } finally { desktopChecking.value = false }
}
async function applyDesktopUpdate() {
  if (desktopApplying.value || !isDesktopShell) return
  openConfirmModal(t('更新启动器将中断正在运行的任务并自动重启程序，确定继续？'), async () => {
    desktopApplying.value = true
    // A successful apply exits and relaunches the shell, so the invoke may
    // never resolve; a rejection carries the failure reason as a string.
    let failed = false
    desktopInvoke()('desktop_update_apply').catch((exception: any) => {
      failed = true
      desktopApplying.value = false
      error.value = String(exception?.message || exception)
    })
    // The download runs while the old backend is still answering, so a live
    // status endpoint does not mean the update finished.  Wait for the
    // backend to go down first (the shell exited for replacement)…
    let shellExited = false
    for (let round = 0; round < 60 && !failed; round++) {
      await new Promise(resolve => setTimeout(resolve, 3000))
      try { await api.get('/api/system/status') } catch { shellExited = true; break }
    }
    if (failed) return
    if (!shellExited) {
      desktopApplying.value = false
      error.value = t('更新超时，请手动刷新页面')
      return
    }
    // …then wait for the new process to serve again and reload for a fresh
    // state.  The success toast is shown after the reload via a flag.
    sessionStorage.setItem('nkas-desktop-updated', '1')
    for (let round = 0; round < 60; round++) {
      await new Promise(resolve => setTimeout(resolve, 3000))
      try { await api.get('/api/system/status'); window.location.reload(); return } catch { }
    }
    sessionStorage.removeItem('nkas-desktop-updated')
    desktopApplying.value = false
    error.value = t('重启超时，请手动刷新页面')
  })
}
// The launcher checks for its own updates once in the background at startup;
// surface the same kind of toast as the source updater when it found one.
async function notifyDesktopUpdate() {
  if (!isDesktopShell) return
  try { desktopUpdate.value = await desktopInvoke()('desktop_update_status') } catch { return }
  if (desktopUpdate.value?.updateAvailable) notify(t('启动器有新版本，可在更新页更新'), 'ok', 0, { label: t('前往更新'), run: () => router.push('/settings') })
}
async function checkUpdate() {
  if (updateChecking.value) return
  updateChecking.value = true
  try {
    await api.post('/api/update/check')
    // Poll until the background check finishes so the button can switch to
    // the update action when a new version shows up.
    for (let round = 0; round < 30; round++) {
      await new Promise(resolve => setTimeout(resolve, 2000))
      updateInfo.value = await api.get('/api/system/update')
      if (updateInfo.value.state !== 'checking') break
    }
  } catch (exception: any) { error.value = exception.message } finally { updateChecking.value = false }
}
const updating = ref(false)
function runUpdate() {
  if (updating.value) return
  openConfirmModal(t('更新源码将等待当前任务执行完毕后再进行，期间请勿启动新任务，确定继续？'), executeSourceUpdate)
}
async function executeSourceUpdate() {
  updating.value = true
  try {
    await api.post('/api/update')
    // The updater first waits for running instances to stop, then pulls and
    // reloads the backend; poll until it leaves the in-progress states.
    let state = ''
    let round = 0
    for (; round < 300; round++) {
      await new Promise(resolve => setTimeout(resolve, 2000))
      // A failed request just means the backend is mid-reload; keep polling.
      try { updateInfo.value = await api.get('/api/system/update') } catch { continue }
      state = String(updateInfo.value.state)
      if (!['checking', 'start', 'wait', 'run update'].includes(state)) break
    }
    if (state === 'failed') {
      error.value = t('更新失败')
      return
    }
    if (round >= 300) {
      error.value = t('更新超时，请稍后手动刷新页面')
      return
    }
    // We initiated this update, so any terminal state other than "failed"
    // means the cycle completed.  In particular a backend reload resets the
    // updater state to idle (0/false); if the reload fits between two polls
    // neither "finish"/"reload" nor a failed request is ever observed, and
    // treating only those as success would silently skip the page reload.
    notify(t('更新完成，正在刷新页面…'))
    for (let waitRound = 0; waitRound < 60; waitRound++) {
      try { await api.get('/api/system/status'); break } catch { await new Promise(resolve => setTimeout(resolve, 2000)) }
    }
    window.location.reload()
  } catch (exception: any) { error.value = exception.message } finally { updating.value = false }
}
const restarting = ref(false)
function forceRestart() {
  if (restarting.value) return
  openConfirmModal(t('强制重启将中断正在运行的任务，确定继续？'), executeForceRestart)
}
async function executeForceRestart() {
  restarting.value = true
  try { await api.post('/api/restart') } catch (exception: any) { error.value = exception.message; restarting.value = false; return }
  // The backend tears itself down right after answering; give it a moment to
  // go down, then poll until it is back and reload for a fresh state.
  notify(t('后端正在重启，页面将自动刷新…'), 'ok', 4000)
  await new Promise(resolve => setTimeout(resolve, 3000))
  for (let round = 0; round < 60; round++) {
    try { await api.get('/api/system/status'); window.location.reload(); return } catch { await new Promise(resolve => setTimeout(resolve, 2000)) }
  }
  error.value = t('重启超时，请手动刷新页面')
  restarting.value = false
}
async function saveRemark(instance: Instance, event: Event) {
  const input = event.target as HTMLInputElement
  try {
    const result = await api.post(`/api/${instance.name}/remark`, { remark: input.value.trim() })
    instance.remark = result.remark
    input.value = result.remark
  } catch (exception: any) { error.value = exception.message; input.value = instance.remark || '' }
}
async function importInstance(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; try { const response = await fetch('/api/instances/import', { method: 'POST', headers: { 'X-NKAS-Filename': file.name }, body: await file.arrayBuffer() }); const result = await response.json(); if (!response.ok) throw new Error(result.message); await loadInstances() } catch (exception: any) { error.value = exception.message } }
async function dismissNotice(notice: any) { try { await api.post(`/api/system/notices/${notice.key}/dismiss`); notices.value = notices.value.filter(item => item.key !== notice.key) } catch (exception: any) { error.value = exception.message } }
// Announcement center: persistent announcements (with history) from the
// backend, shown in a master-detail modal.  `read` comes from the server and
// is flipped locally as soon as an entry is opened.
type Announcement = { id: string; date: string; title: string; type: string; content: string; read: boolean }
const announcements = ref<Announcement[]>([])
const announcementCenterOpen = ref(false)
const activeAnnouncementId = ref('')
let announcementAutoShown = false
const unreadAnnouncementCount = computed(() => announcements.value.filter(item => !item.read).length)
const activeAnnouncement = computed(() => announcements.value.find(item => item.id === activeAnnouncementId.value))
function openAnnouncementCenter() {
  announcementCenterOpen.value = true
  const target = announcements.value.find(item => !item.read) || announcements.value[0]
  if (target) selectAnnouncement(target)
}
async function selectAnnouncement(announcement: Announcement) {
  activeAnnouncementId.value = announcement.id
  if (announcement.read) return
  // Optimistic local read so the badge updates immediately; roll back when
  // the mark-read call fails.
  announcement.read = true
  try { await api.post('/api/system/notices/read', { ids: [announcement.id] }) } catch (exception: any) { announcement.read = false; error.value = exception.message }
}
// Legacy toast parity: sha + commit count headline, then up to 5 messages
// trimmed to 54 chars, one per line.
function autoUpdateTitle(data: any) {
  const sha = String(data?.to_sha || '').trim() || '-'
  const messages = Array.isArray(data?.messages) ? data.messages : []
  const count = Number(data?.commit_count) > 0 ? Number(data.commit_count) : messages.length
  if (systemStatus.value.language === 'en-US') return `Auto-updated to ${sha} (${count} commits)`
  if (systemStatus.value.language === 'ja-JP') return `自動更新完了: ${sha}（${count}件）`
  return `已自动更新到 ${sha}（${count} 条提交）`
}
function autoUpdatePreview(data: any) {
  if (!Array.isArray(data?.messages)) return []
  return data.messages.map((msg: any) => String(msg).trim()).filter(Boolean).slice(0, 5).map((msg: string) => msg.length > 54 ? `${msg.slice(0, 51)}...` : msg)
}
function startStateSocket() {
  stateSocket?.close()
  stateSocket = new JsonSocket('/ws/state', event => { const instance = instances.value.find(item => item.name === event.name); if (instance) instance.state = event.state })
  stateSocket.connect()
}
function startSockets() {
  // Log and queue sockets are per instance; keep them alive while moving
  // between pages of the same instance so logs keep collecting and the
  // replay is not duplicated on return.
  if (!selectedName.value || socketsName === selectedName.value) return
  logSocket?.close(); queueSocket?.close()
  socketsName = selectedName.value
  logSocket = new JsonSocket(`/ws/${selectedName.value}/log`, event => pushLogs(event.html))
  queueSocket = new JsonSocket(`/ws/${selectedName.value}/queue`, event => queue.value = event)
  logSocket.connect(); queueSocket.connect()
}
// Backend restart self-healing: the legacy Electron shell never reloads the
// page, so poll the status endpoint and reload everything once it recovers.
// The status payload also carries updater_state; surface a toast when an
// automatic check (startup or scheduled) discovers a new version while the
// user is somewhere else in the app.
let lastUpdaterState: any = undefined
function watchUpdaterState(state: any) {
  const available = state === true || state === 1
  if (available && !(lastUpdaterState === true || lastUpdaterState === 1)) notify(t('发现新版本，可在更新页更新'), 'ok', 0, { label: t('前往更新'), run: () => router.push('/settings') })
  if (updateInfo.value && typeof updateInfo.value === 'object' && 'state' in updateInfo.value) updateInfo.value.state = state
  lastUpdaterState = state
}
async function healthCheck() {
  try {
    const status = await api.get('/api/system/status')
    watchUpdaterState(status.updater_state)
    if (backendDown.value) {
      backendDown.value = false
      workspaceName = ''
      socketsName = ''
      await loadSystem(); await loadInstances(); await loadWorkspace(); startStateSocket(); startSockets()
    }
  } catch {
    backendDown.value = true
  }
}
onMounted(async () => { if (sessionStorage.getItem('nkas-desktop-updated')) { sessionStorage.removeItem('nkas-desktop-updated'); notify(t('启动器更新完成'), 'ok', 4000) } if (isTauri) { syncMaximized(); window.addEventListener('resize', syncMaximized) } await loadSystem(); await notifyDesktopUpdate(); await loadInstances(); if (route.path === '/' && systemStatus.value.home_page === 'instance' && instances.value.length) { router.replace(`/i/${instances.value[0].name}/overview`) } else { await loadWorkspace() } startStateSocket(); startSockets(); if (isDeploy.value) await loadDeploy(); if (isLogs.value) await refreshLogs(); healthTimer = window.setInterval(healthCheck, 4000) })
watch(() => route.fullPath, async () => {
  // 路由变化时收起移动端抽屉，避免残留遮挡主内容。
  mobileNav.value = ''
  // Only a different instance needs a schema reload and socket swap; task
  // switches and global pages retain the current instance's log scrollback.
  if (selectedName.value && selectedName.value !== workspaceName) {
    logs.value = []
    await loadWorkspace()
  }
  activeGroup.value = taskSchema.value?.groups?.[0]?.key || ''
  startSockets()
  if (isSettings.value) { await refreshUpdateInfo(); await refreshDesktopUpdate() }
  else { window.clearTimeout(updatePollTimer); window.clearTimeout(desktopUpdatePollTimer) }
  if (isDeploy.value) await loadDeploy()
  if (isLogs.value) await refreshLogs()
})
watch(logTick, async () => { if (autoScroll.value) { await nextTick(); if (logBody.value) logBody.value.scrollTop = logBody.value.scrollHeight } })
// 抽屉打开时锁定背景滚动，避免移动端误触翻页。
watch(mobileNav, open => { document.body.style.overflow = open ? 'hidden' : '' })
onBeforeUnmount(() => {
  document.body.style.overflow = ''
  window.removeEventListener('resize', syncMaximized)
  stateSocket?.close()
  logSocket?.close()
  queueSocket?.close()
  window.clearInterval(healthTimer)
  window.clearTimeout(updatePollTimer)
  window.clearTimeout(desktopUpdatePollTimer)
  datetimeSaveTimers.forEach(timer => window.clearTimeout(timer))
  datetimeSaveTimers.clear()
})
</script>

<template>
  <div class="app" :class="{ 'legacy-electron': legacyElectron, 'side-collapsed': sidebarCollapsed }">
    <div class="app-body">
    <nav class="sidebar" :class="{ 'mobile-open': mobileNav === 'sidebar' }">
      <div class="brand" @mousedown="onBrandMouseDown">
        <img class="brand-logo brand-logo-img" :src="brandIcon" alt="NKAS">
        <div class="brand-text"><div class="brand-name">NKAS</div><div class="brand-sub">NIKKE AUTO SCRIPT</div></div>
        <button class="side-toggle" @click="sidebarCollapsed = !sidebarCollapsed">{{ sidebarCollapsed ? '»' : '«' }}</button>
      </div>
      <div class="side-section">
        <button class="side-item" :class="{ active: isDashboard }" @click="dashboard"><span class="sicon">📊</span><span class="side-text">{{ t('总览') }}</span></button>
      </div>
      <div class="side-section">
        <div class="side-label">{{ t('实例') }}</div>
        <button v-for="instance in instances" :key="instance.name" class="side-item" :class="{ active: selectedName === instance.name }" @click="enter(instance.name)">
          <span class="inst-avatar" :class="{ idle: instance.state !== 1 }">{{ initials(instance.name) }}<span class="ring" :class="stateClass(instance.state)"></span></span>
          <span class="side-text">{{ instance.name }}</span>
          <span class="badge" :class="{ 'idle-badge': instance.state !== 1 }">{{ instance.state === 1 ? t('运行中') : t('空闲') }}</span>
        </button>
      </div>
      <div class="side-section">
        <div class="side-label">{{ t('系统') }}</div>
        <button class="side-item" :class="{ active: isManage }" @click="router.push('/manage')"><span class="sicon">🗂</span><span class="side-text">{{ t('多开') }}</span></button>
        <button class="side-item" :class="{ active: isDeploy }" @click="router.push('/deploy')"><span class="sicon">📦</span><span class="side-text">{{ t('部署') }}</span></button>
        <button class="side-item" :class="{ active: isLogs }" @click="router.push('/logs')"><span class="sicon">📄</span><span class="side-text">{{ t('日志') }}</span></button>
        <button class="side-item" :class="{ active: isSettings }" @click="router.push('/settings')"><span class="sicon">⚙️</span><span class="side-text">{{ t('更新') }}</span></button>
        <button class="side-item" :class="{ active: isAbout }" @click="router.push('/about')"><span class="sicon">ℹ️</span><span class="side-text">{{ t('关于') }}</span></button>
      </div>
      <div class="side-spacer"></div>
      <div class="side-footer">
        <button class="icon-btn" @click="toggleTheme">{{ systemStatus.theme === 'dark' ? '🌙' : '☀️' }} <span class="side-text">{{ t('主题') }}</span></button>
        <AppSelect class="lang-select" :model-value="systemStatus.language" :options="languageOptions" @change="setLanguage"/>
      </div>
    </nav>
    <aside v-if="isWorkspace" class="rail" :class="{ 'mobile-open': mobileNav === 'rail' }">
      <div class="rail-head">
        <div class="rail-inst">
          <span class="inst-avatar" :class="{ idle: selectedInstance?.state !== 1 }">{{ initials(selectedName) }}<span class="ring" :class="stateClass(selectedInstance?.state)"></span></span>
          <div><div class="rail-inst-name">{{ selectedName }}</div><div class="rail-inst-state">{{ stateText(selectedInstance?.state) }}</div></div>
        </div>
        <label class="rail-search">🔍 <input v-model="taskFilter" :placeholder="t('筛选任务…')"><button v-if="taskFilter" type="button" class="rail-clear" @click.prevent="taskFilter = ''">✕</button></label>
      </div>
      <div class="rail-list">
        <button class="rail-item" :class="{ active: selectedPage === 'overview' }" @click="router.push(`/i/${selectedName}/overview`)">📈 {{ t('任务总览') }}</button>
        <template v-if="schemaReady" v-for="menu in visibleMenus" :key="menu.key">
          <button class="rail-group" :class="{ expanded: !railCollapsed[menu.key] || taskFilter }" @click="toggleRail(menu)">
            <span class="chev">›</span><span class="sicon">{{ menu.icon || '•' }}</span>{{ menu.name }}
            <span class="rail-count">{{ menu.tasks.filter((task: any) => taskEnabled(task.key)).length }}/{{ menu.tasks.length }}</span>
          </button>
          <div v-show="!railCollapsed[menu.key] || taskFilter" class="rail-tasks">
            <button v-for="task in menu.tasks" :key="task.key" class="rail-item" :class="{ active: selectedTask === task.key }" @click="openTask(task, menu.page === 'tool' ? 'tool' : 'task')">
              {{ task.name }}
              <span v-if="selectedInstance?.current_task === task.key" class="spin"></span>
              <span v-else-if="taskEnabled(task.key)" class="mini-dot on"></span>
            </button>
          </div>
        </template>
      </div>
    </aside>
    <main class="main">
      <header class="topbar" @mousedown="onTopbarMouseDown">
        <button class="tb-btn tb-menu" :title="t('菜单')" @click="mobileNav = mobileNav === 'sidebar' ? '' : 'sidebar'">
          <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"><path d="M3 5.5h14M3 10h14M3 14.5h14"/></svg>
        </button>
        <div class="crumb"><span v-if="isWorkspace" class="pre">{{ selectedName }} /</span><span class="cur">{{ pageTitle() }}</span></div>
        <span v-if="isWorkspace" class="status-pill" :class="stateClass(selectedInstance?.state)">{{ stateText(selectedInstance?.state) }}</span>
        <div class="topbar-right">
          <button class="tb-btn tb-bell" :title="t('公告中心')" @click="openAnnouncementCenter">
            <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M10 3.2a4.6 4.6 0 0 0-4.6 4.6v2.6c0 .5-.17 1-.47 1.42l-1.05 1.5h12.24l-1.05-1.5a2.3 2.3 0 0 1-.47-1.42V7.8A4.6 4.6 0 0 0 10 3.2Z"/><path d="M8.3 15.6a1.8 1.8 0 0 0 3.4 0"/></svg>
            <span v-if="unreadAnnouncementCount" class="tb-badge">{{ unreadAnnouncementCount > 99 ? '99+' : unreadAnnouncementCount }}</span>
          </button>
          <template v-if="isTauri">
            <button class="tb-btn" :title="t('隐藏到托盘')" @click="tbHide"><svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M10 4v7"/><path d="M6.5 8 10 11.5 13.5 8"/><path d="M4 15.5h12"/></svg></button>
            <button class="tb-btn" :title="t('最小化')" @click="tbMinimize"><svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"><path d="M5 10.5h10"/></svg></button>
            <button class="tb-btn" :title="isMaximized ? t('还原') : t('最大化')" @click="tbToggleMaximize">
              <svg v-if="!isMaximized" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.6"><rect x="5.5" y="5.5" width="9" height="9" rx="1"/></svg>
              <svg v-else viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.6"><rect x="4" y="7.5" width="8" height="8" rx="1"/><path d="M8 7.5v-2A1.5 1.5 0 0 1 9.5 4h5A1.5 1.5 0 0 1 16 5.5v5a1.5 1.5 0 0 1-1.5 1.5h-2"/></svg>
            </button>
            <button class="tb-btn tb-close" :title="t('关闭')" @click="tbClose"><svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"><path d="M6 6l8 8M14 6l-8 8"/></svg></button>
          </template>
        </div>
      </header>
      <MaintenanceBanner :language="systemStatus.language" />
      <div v-if="notices.length" class="notice-stack">
        <article v-for="notice in notices" :key="notice.key" class="notice-card" :class="notice.type">
          <div>
            <strong>{{ notice.key === 'auto_update' ? autoUpdateTitle(notice.data) : (notice.data.title || t('系统通知')) }}</strong>
            <ul v-if="autoUpdatePreview(notice.data).length" class="notice-messages">
              <li v-for="(msg, index) in autoUpdatePreview(notice.data)" :key="index">• {{ msg }}</li>
            </ul>
            <p v-else>{{ notice.data.content || notice.data.error || t('有新的系统通知。') }}</p>
          </div>
          <button class="btn sm" @click="dismissNotice(notice)">{{ t('知道了') }}</button>
        </article>
      </div>
      <div class="toast-stack">
        <div v-for="toast in toasts" :key="toast.id" class="toast" :class="toast.kind"><span>{{ toast.kind === 'error' ? '✕' : '✓' }} {{ toast.text }}</span><button v-if="toast.action" type="button" class="toast-action" @click="toast.action.run(); closeToast(toast.id)">{{ toast.action.label }}</button><button type="button" class="toast-close" @click="closeToast(toast.id)">✕</button></div>
      </div>
      <section v-if="isDashboard" class="view">
        <div class="stat-row">
          <article class="card stat-card hoverable"><div class="stat-icon blue">🖥️</div><div><div class="stat-num">{{ instances.length }}</div><div class="stat-lbl">{{ t('实例总数') }}</div></div></article>
          <article class="card stat-card hoverable"><div class="stat-icon green">▶️</div><div><div class="stat-num" style="color:var(--green)">{{ runningCount }}</div><div class="stat-lbl">{{ t('运行中') }}</div></div></article>
        </div>
        <div class="section-title">{{ t('实例') }}</div>
        <div class="inst-grid">
          <article v-for="instance in instances" :key="instance.name" class="card inst-card hoverable" :class="{ 'is-running': instance.state === 1 }">
            <div class="inst-card-head">
              <span class="inst-avatar" :class="{ idle: instance.state !== 1 }">{{ initials(instance.name) }}<span class="ring" :class="stateClass(instance.state)"></span></span>
              <div><h3>{{ instance.name }}</h3><div v-if="instance.mod !== 'nkas'" class="sub">mod: {{ instance.mod }}</div></div>
              <span class="status-pill" :class="stateClass(instance.state)" style="margin-left:auto"><span v-if="instance.state === 1" class="pulse"></span>{{ instance.state === 1 ? t('运行中') : t('待机') }}</span>
            </div>
            <div class="inst-now"><span class="k">{{ t('当前任务') }}</span><span>{{ instance.current_task || t('无') }}</span></div>
            <div class="inst-now"><span class="k">{{ t('下一任务') }}</span><span>{{ instance.next_task || '—' }}</span></div>
            <div class="inst-card-foot">
              <button class="btn sm" :class="instance.state === 1 ? 'danger' : 'success'" style="flex:1" @click="lifecycle(instance.state === 1 ? 'stop' : 'start', instance.name)">{{ instance.state === 1 ? t('停止') : t('启动') }}</button>
              <button class="btn primary sm" style="flex:1" @click="enter(instance.name)">{{ t('进入 →') }}</button>
            </div>
          </article>
          <button class="card add-card" @click="openCreateModal"><span class="plus">＋</span>{{ t('新建实例') }}</button>
        </div>
        <EventCalendar :language="systemStatus.language" @error="calendarError" />
      </section>
      <section v-else-if="isWorkspace && selectedPage === 'overview'" class="view">
        <div class="ov-layout">
          <div class="ov-left">
            <article class="card hero-sched">
              <div style="flex:1"><b>{{ t('调度器') }}</b></div>
              <button class="btn" :class="selectedInstance?.state === 1 ? 'danger' : 'success'" @click="lifecycle(selectedInstance?.state === 1 ? 'stop' : 'start')">{{ selectedInstance?.state === 1 ? t('停止') : t('启动') }}</button>
            </article>
            <article class="card queue-card">
              <div class="timeline">
                <div class="tl-label">{{ t('运行中') }}</div>
                <div v-for="item in queue.running || []" :key="item.command" class="tl-item running clickable" @click="openQueueItem(item)">{{ item.name_i18n }}<span class="t">{{ formatTime(item.next_run) }}</span><span class="go">›</span></div>
                <div v-if="!queue.running?.length" class="tl-item placeholder">{{ t('暂无运行任务') }}</div>
                <div class="tl-label">{{ t('队列中') }}</div>
                <div v-for="item in queue.pending || []" :key="item.command" class="tl-item clickable" @click="openQueueItem(item)">{{ item.name_i18n }}<span class="t">{{ formatTime(item.next_run) }}</span><span class="go">›</span></div>
                <div v-if="!queue.pending?.length" class="tl-item placeholder">{{ t('队列为空') }}</div>
              </div>
            </article>
            <article class="card queue-card">
              <div class="queue-group-label">{{ t('等待中') }}</div>
              <div class="timeline">
                <template v-for="(item, index) in queue.waiting || []" :key="item.command">
                  <div v-if="index > 0 && dayOf(item.next_run) !== dayOf(queue.waiting[index - 1].next_run)" class="tl-date-sep"><span>{{ formatDate(item.next_run) }}</span></div>
                  <div class="tl-item clickable" @click="openQueueItem(item)">{{ item.name_i18n }}<span class="t">{{ formatTime(item.next_run) }}</span><span class="go">›</span></div>
                </template>
              </div>
            </article>
          </div>
          <article class="card log-card">
            <div class="log-head"><b>{{ t('实时日志') }}</b><span class="log-autoscroll"><AppSelect class="log-level-select" v-model="logLevel" :options="logLevelOptions"/><label class="switch sm"><input v-model="autoScroll" type="checkbox"><span class="slider"></span></label>{{ t('自动滚动') }}</span></div>
            <div ref="logBody" class="log-body">
              <div v-for="line in visibleLogs" :key="line.id" class="log-frag" v-html="line.html"></div>
            </div>
          </article>
        </div>
      </section>
      <section v-else-if="isWorkspace" class="view" :class="{ 'tool-view': selectedPage === 'tool' }" @scroll.passive="onViewScroll">
        <div class="task-layout">
          <div>
            <article class="card task-hero">
              <div class="task-icon">{{ selectedPage === 'tool' ? '🛠' : '⚙️' }}</div>
              <div style="flex:1"><h2>{{ taskSchema?.name || selectedTask }}</h2><div class="sub">{{ taskSchema?.help || '' }}</div></div>
              <button v-if="selectedPage === 'tool'" class="btn" :class="selectedInstance?.state === 1 ? 'danger' : 'primary'" @click="selectedInstance?.state === 1 ? lifecycle('stop') : api.post(`/api/${selectedName}/tool/${selectedTask}/start`).catch(exception => error = exception.message)">{{ selectedInstance?.state === 1 ? t('停止') : `▶ ${t('启动')}` }}</button>
            </article>
            <div class="cfg-groups">
              <article v-for="group in taskSchema?.groups || []" :id="groupId(group)" :key="group.key" class="card group-card" :class="{ collapsed: collapsed[group.key] }">
                <button class="group-head" @click="collapsed[group.key] = !collapsed[group.key]">
                  <h4>{{ group.name }}</h4>
                  <span class="group-summary">›</span>
                </button>
                <div class="group-body">
                  <div v-for="field in group.fields" :key="field.key" class="field" :class="{ 'field-wide': isWideField(field) }">
                    <div class="field-label"><div class="fname">{{ field.title }}</div><div v-if="field.help" class="fhelp">{{ field.help }}</div></div>
                    <div class="field-control">
                      <label v-if="field.widget === 'checkbox'" class="switch"><input type="checkbox" :checked="field.value" :disabled="field.display !== 'show'" @change="save(field, $event)"><span class="slider"></span></label>
                      <AppSelect v-else-if="field.widget === 'select'" :model-value="field.value" :options="field.options" :disabled="field.display !== 'show'" @change="(value: any) => saveValue(field, value).catch(() => {})"/>
                      <template v-else-if="field.path_picker">
                        <div class="path-field">
                          <input type="text" :value="field.value" :readonly="field.display !== 'show'" @change="save(field, $event)">
                          <FieldPathPicker :value="field.value" :picker="field.path_picker" :disabled="field.display !== 'show'" @picked="pickedPath(field, $event)" @error="error = $event"/>
                        </div>
                      </template>
                      <div v-else-if="field.widget === 'textarea'" class="code-wrap">
                        <pre v-if="isStructuredTextarea(field)" class="code-highlight" v-html="highlightTextarea(field)"></pre>
                        <textarea v-autosize :class="{ 'code-input': isStructuredTextarea(field), 'textarea-mono': field.mode !== 'text' }" :value="field.value" :readonly="field.display !== 'show'" :inputmode="field.mode === 'url' ? 'url' : 'text'" spellcheck="false" @input="resizeTextarea" @change="save(field, $event)"></textarea>
                      </div>
                      <FieldItemTable v-else-if="field.widget === 'item_table'" :data="field.special_data" :loading="!field.special_data"/>
                      <FieldPriority v-else-if="field.widget === 'priority'" :value="field.value" :options="field.options" :disabled="field.display !== 'show'" :placeholder="t('添加')" @change="(value: string) => saveValue(field, value).catch(() => {})"/>
                      <FieldInterception v-else-if="field.widget === 'interception_stone_import'" :widget="field.widget" :busy="Boolean(importBusy[field.key])" @import="importInterception(field, $event)" @error="error = $event"/>
                      <FieldInterception v-else-if="field.widget === 'interception_stone_charts'" :widget="field.widget" :data="field.special_data"/>
                      <template v-else-if="field.widget === 'datetime'">
                        <div class="dt-field">
                          <input type="datetime-local" :value="datetimeValue(field.value)" :readonly="field.display !== 'show'" @input="scheduleDatetimeSave(field, $event)" @blur="flushDatetimeSave(field, $event)">
                          <button v-if="field.display === 'show'" type="button" class="dt-clear" :title="t('清空')" @mousedown.prevent @click="clearField(field)">✕</button>
                        </div>
                      </template>
                      <input v-else :type="field.key.endsWith('.Password') ? 'password' : 'text'" :value="field.value" :readonly="field.display !== 'show'" @change="save(field, $event)">
                    </div>
                  </div>
                  <div v-if="selectedTask === 'NKAS' && group.key === 'Notification'" class="field">
                    <div class="field-label"><div class="fname">{{ t('测试通知') }}</div><div class="fhelp">{{ t('发送一条测试通知，验证当前通知设置是否生效。') }}</div></div>
                    <div class="field-control"><button class="btn" :disabled="notifyTestBusy" @click="testNotify">{{ notifyTestBusy ? t('发送中…') : t('测试通知') }}</button></div>
                  </div>
                </div>
              </article>
            </div>
            <article v-if="selectedTask && schemaReady && !taskSchema" class="card group-card">
              <div class="group-body special-empty" style="padding:16px 22px">{{ t('未知任务') }}: {{ selectedTask }}</div>
            </article>
            <article v-if="selectedPage === 'tool'" class="card log-card tool-log">
              <div class="log-head"><b>{{ t('实时日志') }}</b><span class="log-autoscroll"><AppSelect class="log-level-select" v-model="logLevel" :options="logLevelOptions"/><label class="switch sm"><input v-model="autoScroll" type="checkbox"><span class="slider"></span></label>{{ t('自动滚动') }}</span></div>
              <div ref="logBody" class="log-body">
                <div v-for="line in visibleLogs" :key="line.id" class="log-frag" v-html="line.html"></div>
              </div>
            </article>
          </div>
          <aside class="card anchor-nav">
            <div class="side-label">{{ t('本页分组') }}</div>
            <button v-for="group in taskSchema?.groups || []" :key="group.key" class="anchor-nav-item" :class="{ active: activeGroup === group.key }" @click="jumpToGroup(group)">{{ group.name }}</button>
          </aside>
        </div>
      </section>
      <section v-else-if="isManage" class="view">
        <article class="card task-hero">
          <div class="task-icon">🗂</div>
          <div style="flex:1"><h2>{{ t('多开') }}</h2><div class="sub">{{ t('实例总数') }}: {{ instances.length }}</div></div>
          <button class="btn primary" @click="openCreateModal">{{ t('＋ 新建实例') }}</button>
          <label class="btn">⤒ {{ t('导入配置') }}<input type="file" accept=".json" hidden @change="importInstance"></label>
        </article>
        <article class="card manage-table" style="overflow:hidden">
          <table>
            <colgroup><col style="width:22%"><col style="width:10%"><col style="width:15%"><col><col style="width:200px"></colgroup>
            <thead><tr><th>{{ t('名称') }}</th><th>Mod</th><th>{{ t('状态') }}</th><th>{{ t('备注') }}</th><th>{{ t('操作') }}</th></tr></thead>
            <tbody>
              <tr v-for="instance in instances" :key="instance.name">
                <td :data-label="t('名称')"><span class="cell-inst"><span class="inst-avatar" :class="{ idle: instance.state !== 1 }">{{ initials(instance.name) }}<span class="ring" :class="stateClass(instance.state)"></span></span>{{ instance.name }}</span></td>
                <td :data-label="t('Mod')">{{ instance.mod }}</td>
                <td :data-label="t('状态')"><span class="status-pill" :class="stateClass(instance.state)">{{ stateText(instance.state) }}</span></td>
                <td :data-label="t('备注')"><input class="remark-input" :value="instance.remark" placeholder="—" @change="saveRemark(instance, $event)"></td>
                <td :data-label="t('操作')"><a class="btn sm" :href="`/api/${instance.name}/export`">{{ t('导出') }}</a> <button class="btn danger sm" :disabled="instance.state === 1" @click="openDeleteModal(instance.name)">{{ t('删除') }}</button></td>
              </tr>
            </tbody>
          </table>
        </article>
      </section>
      <section v-else-if="isSettings" class="view">
        <article class="card task-hero">
          <div class="task-icon">🖥️</div>
          <div style="flex:1"><h2>{{ t('启动器更新') }}</h2><div class="sub">{{ t('更新nkas程序（exe）本身') }}<span v-if="!isDesktopShell" class="desktop-only-hint"> · {{ t('此功能仅在1.x版本中可用') }}</span></div>
            <div class="sub">{{ t('当前版本') }} <code class="ver-pill">{{ desktopUpdate?.currentVersion || '—' }}</code><span v-if="desktopUpdate?.updateAvailable" class="update-hint"> · {{ t('有新版本可用') }}</span><span v-else-if="desktopUpdate?.checked && !desktopUpdate?.error" class="sub"> · {{ t('已是最新') }}</span><span v-if="desktopUpdate?.error" class="update-hint"> · {{ desktopUpdate.error }}</span></div>
          </div>
          <button v-if="desktopUpdate?.updateAvailable" class="btn success" :disabled="!isDesktopShell || desktopApplying || desktopUpdate?.applying" @click="applyDesktopUpdate"><span v-if="desktopApplying || desktopUpdate?.applying" class="btn-spin"></span>{{ desktopApplying || desktopUpdate?.applying ? t('更新中…') : t('立即更新') }}</button>
          <button v-else class="btn primary" :disabled="!isDesktopShell || desktopChecking || desktopApplying || desktopUpdate?.checking || desktopUpdate?.applying" @click="checkDesktopUpdate"><span v-if="desktopChecking || desktopApplying || desktopUpdate?.checking || desktopUpdate?.applying" class="btn-spin"></span>{{ desktopApplying || desktopUpdate?.applying ? t('更新中…') : (desktopChecking || desktopUpdate?.checking ? t('检查中…') : t('检查更新')) }}</button>
        </article>
        <article class="card task-hero">
          <div class="task-icon">🚀</div>
          <div style="flex:1"><h2>{{ t('源码更新') }}</h2><div class="sub">{{ t('当前版本') }} <code class="ver-pill">{{ systemStatus.version }}</code><span v-if="Number(updateInfo.state) === 1" class="update-hint"> · {{ t('有新版本可用') }}</span><span v-else-if="Number(updateInfo.state) === 0" class="sub"> · {{ t('已是最新') }}</span></div></div>
          <button v-if="Number(updateInfo.state) === 1" class="btn success" :disabled="updating" @click="runUpdate"><span v-if="updating" class="btn-spin"></span>{{ updating ? t('更新中…') : t('立即更新') }}</button>
          <button v-else-if="updateInfo.state === 'failed'" class="btn danger" :disabled="updating" @click="runUpdate"><span v-if="updating" class="btn-spin"></span>{{ updating ? t('更新中…') : t('重试更新') }}</button>
          <button v-else class="btn primary" :disabled="updating || updateChecking || updateInfo.state === 'checking'" @click="checkUpdate">{{ updating ? t('更新中…') : (updateChecking || updateInfo.state === 'checking' ? t('检查中…') : t('检查更新')) }}</button>
          <button class="btn danger" :disabled="restarting" @click="forceRestart"><span v-if="restarting" class="btn-spin"></span>{{ restarting ? t('重启中…') : t('强制重启') }}</button>
        </article>
        <article class="card group-card">
          <div class="group-head"><h4>{{ t('更新记录') }}</h4></div>
          <div class="group-body history-body">
            <div v-for="commit in updateInfo.history || []" :key="commit[0]" class="history-row" :class="{ current: updateInfo.local && commit[0] === updateInfo.local[0] }"><span class="msg">{{ commit[3] }}</span><small><code>{{ commit[0] }}</code><span v-if="updateInfo.local && commit[0] === updateInfo.local[0]" class="current-pill">{{ t('当前版本') }}</span>{{ String(commit[2] || '').slice(0, 10) }}</small></div>
          </div>
        </article>
      </section>
      <section v-else-if="isDeploy" class="view">
        <article class="card task-hero">
          <div class="task-icon">📦</div>
          <div style="flex:1"><h2>{{ t('部署') }}</h2><div class="sub deploy-warning">⚠ {{ t('修改部署配置可能导致更新失败或程序无法启动，修改需要重启后生效，请谨慎操作。') }}</div></div>
          <button class="btn danger" @click="openResetDeployModal">{{ t('还原默认') }}</button>
        </article>
        <div class="cfg-groups">
          <article v-for="group in deployGroups" :key="group.key" class="card group-card">
            <div class="group-head"><h4>{{ group.name }}</h4></div>
            <div class="group-body">
              <div v-for="field in group.fields" :key="field.key" class="field" :class="{ 'field-wide': field.wide }">
                <div class="field-label"><div class="fname">{{ field.title }}</div><div v-if="field.help" class="fhelp">{{ field.help }}</div><div v-for="hint in field.hints || []" :key="hint.tag" class="deploy-hint"><span class="deploy-hint-tag">{{ hint.tag }}</span><span>{{ hint.text }}</span></div></div>
                <div class="field-control">
                  <label v-if="field.widget === 'checkbox'" class="switch"><input type="checkbox" :checked="field.value" @change="saveDeployField(field, $event)"><span class="slider"></span></label>
                  <AppSelect v-else-if="field.widget === 'select'" :model-value="field.value" :options="field.options" @change="(value: any) => saveDeployValue(field, value)"/>
                  <div v-else-if="field.widget === 'multiselect'" class="deploy-multisel">
                    <label v-for="opt in field.options" :key="opt.value" class="deploy-multi-opt" :class="{ on: (field.value || []).includes(opt.value) }"><input type="checkbox" hidden :checked="(field.value || []).includes(opt.value)" @change="toggleDeployMulti(field, opt.value)">{{ opt.label }}</label>
                  </div>
                  <input v-else :type="field.widget === 'number' ? 'number' : 'text'" :value="field.value ?? ''" @change="saveDeployField(field, $event)">
                </div>
              </div>
            </div>
          </article>
        </div>
      </section>
      <section v-else-if="isLogs" class="view logs-view">
        <article class="card task-hero">
          <div class="task-icon">📄</div>
          <div style="flex:1"><h2>{{ t('日志') }}</h2><div class="sub">{{ t('查看 log 目录下的日志文件，支持按类型、级别、日期和关键字筛选。') }}</div></div>
          <button class="btn" @click="refreshLogs">↻ {{ t('刷新') }}</button>
        </article>
        <article class="card log-card logs-card">
          <div class="log-head logs-filter">
            <label class="logs-filter-item">{{ t('日期') }}<AppSelect v-model="logsDate" :options="logsDateOptions"/></label>
            <label class="logs-filter-item">{{ t('类型') }}<AppSelect v-model="logsSource" :options="logsSourceOptions"/></label>
            <label class="logs-filter-item">{{ t('级别') }}<AppSelect v-model="logsLevel" :options="logLevelOptions"/></label>
            <label class="logs-filter-item logs-keyword">{{ t('关键字') }}<span class="logs-kw"><input v-model="logsKeyword" :placeholder="t('搜索关键字…')"><button v-if="logsKeyword" type="button" class="logs-kw-clear" @click.prevent="logsKeyword = ''">✕</button></span></label>
            <span class="logs-meta">{{ logsCountText() }}<span v-if="logsLoading"> · …</span></span>
          </div>
          <div ref="logsBody" class="log-body" :class="{ 'logs-merge': !logsSource }">
            <div v-if="!logsRecords.length && !logsLoading" class="logs-empty">{{ t('没有匹配的日志') }}</div>
            <div v-for="(line, index) in logsRecords" :key="index" class="log-line" :class="[logsRankClass(line.rank), line.kind, line.section_level !== undefined ? `section-level-${line.section_level}` : '']">
              <span class="ts">{{ line.time }}</span>
              <span class="lv-chip" :class="logsRankClass(line.rank)">{{ line.level }}</span>
              <span v-if="!logsSource" class="logs-src">{{ line.source }}</span>
              <span v-if="line.kind === 'attr'" class="log-message"><span class="log-attr-key">{{ line.attr_name }}:</span><span class="log-attr-value" :class="`attr-value-${line.attr_value_kind || 'text'}`">{{ line.attr_value }}</span></span>
              <span v-else class="log-message">{{ line.text }}</span>
              <div v-if="line.traceback" class="log-traceback">
                <details v-if="line.traceback_collapsed" class="log-traceback-more">
                  <summary>{{ t('详细信息') }}</summary>
                  <pre class="log-traceback-collapsed">{{ line.traceback_collapsed }}</pre>
                </details>
                <pre class="log-traceback-primary">{{ line.traceback }}</pre>
              </div>
            </div>
          </div>
        </article>
      </section>
      <section v-else class="view">
        <article class="card about-panel">
          <div class="about-hero">
            <img class="brand-logo brand-logo-img" :src="brandIcon" alt="NKAS">
            <div><h2>NKAS · NIKKEAutoScript</h2><div class="sub">NIKKEAutoScript · {{ systemStatus.version }}</div></div>
          </div>
          <p>NKAS is a free open source software, if you paid for NKAS from any channel, please refund.<br>NKAS 是一款免费开源软件，如果你在任何渠道付费购买了NKAS，请退款。</p>
          <h3>Project / 项目</h3>
          <p>
            Project repository / 项目地址：<a href="https://github.com/megumiss/NIKKEAutoScript" target="_blank">https://github.com/megumiss/NIKKEAutoScript</a><br>
            Detailed guide / 详细指南：<a href="https://github.com/megumiss/NIKKEAutoScript/wiki" target="_blank">https://github.com/megumiss/NIKKEAutoScript/wiki</a>
          </p>
          <h3>💡 Need help / 寻求帮助</h3>
          <p>
            If you encounter any issues while using, you can get help through the following ways:<br>
            如果在使用过程中遇到问题，您可以通过以下方式获取帮助：<br>
            Submit an issue / 提交问题：<a href="https://github.com/megumiss/NIKKEAutoScript/issues" target="_blank">GitHub Issues</a><br>
            QQ group / 划水 QQ 群：823265807
          </p>
          <h3>Support / 支持项目</h3>
          <p>
            If you like this project, you can buy the author a cup of Mixue Ice Cream 🍦<br>
            如果喜欢本项目，可以送作者一杯蜜雪冰城🍦<br>
            Your support is the motivation for the author to develop and maintain the project 🚀<br>
            您的支持就是作者开发和维护项目的动力🚀
          </p>
          <div class="about-donations">
            <figure><img :src="'/static/gui/donate/wechat.png'" alt="WeChat Pay"><figcaption>WeChat Pay (微信)</figcaption></figure>
            <figure><img :src="'/static/gui/donate/alipay.png'" alt="Alipay"><figcaption>Alipay (支付宝)</figcaption></figure>
            <figure><img :src="'/static/gui/donate/alipayremit.png'" alt="Alipay Remit"><figcaption>Alipay Remit (For international)</figcaption></figure>
          </div>
        </article>
      </section>
    </main>
    </div>
    <!-- 移动端：贴右边缘的悬浮把手，点击滑出/收起任务列表抽屉 -->
    <button v-if="isWorkspace" class="rail-trigger" :class="{ open: mobileNav === 'rail' }" :title="mobileNav === 'rail' ? t('收起任务列表') : t('任务列表')" @click="mobileNav = mobileNav === 'rail' ? '' : 'rail'">
      <svg v-if="mobileNav === 'rail'" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="m10 6 6 6-6 6"/></svg>
      <svg v-else viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="m14 6-6 6 6 6"/></svg>
    </button>
    <div v-if="mobileNav" class="mobile-scrim" @click="mobileNav = ''"></div>
    <div v-if="backendDown" class="backend-down"><div class="backend-down-card">{{ t('后端连接中断，正在等待恢复…') }}</div></div>
    <div v-if="announcementCenterOpen" class="modal-mask" @click.self="announcementCenterOpen = false">
      <div class="modal-card announcement-card">
        <div class="announcement-head">
          <h3>{{ t('公告中心') }}</h3>
          <button class="tb-btn announcement-close" :title="t('关闭')" @click="announcementCenterOpen = false"><svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"><path d="M6 6l8 8M14 6l-8 8"/></svg></button>
        </div>
        <div class="announcement-body">
          <div class="announcement-list">
            <div v-if="!announcements.length" class="announcement-empty">{{ t('暂无公告') }}</div>
            <button v-for="item in announcements" :key="item.id" class="announcement-item" :class="[{ active: item.id === activeAnnouncementId }, item.type]" @click="selectAnnouncement(item)">
              <span class="announcement-date">{{ item.date }}</span>
              <span class="announcement-title">{{ item.title }}</span>
              <span v-if="!item.read" class="announcement-dot" :title="t('未读')"></span>
            </button>
          </div>
          <!-- 公告正文来自仓库自带的公告文件（可信来源），用 v-html 渲染以支持
               链接与强调；notice-content 的 pre-line 让纯文本公告照常换行 -->
          <div class="modal-text notice-content announcement-content" v-html="activeAnnouncement?.content || ''"></div>
        </div>
      </div>
    </div>
    <div v-if="modal.type" class="modal-mask" @click.self="modal.type = ''">
      <div class="modal-card">
        <h3>{{ modal.type === 'create' ? t('新建实例') : modal.type === 'resetDeploy' ? t('还原默认') : modal.type === 'confirm' ? t('确认') : modal.type === 'alert' ? modalAlertTitle : t('删除') }}</h3>
        <template v-if="modal.type === 'create'">
          <label class="modal-field">{{ t('名称') }}<input v-model="modal.name" @keyup.enter="confirmModal"></label>
          <label class="modal-field">{{ t('复制来源实例') }}<AppSelect v-model="modal.origin" :options="originOptions"/></label>
        </template>
        <template v-else-if="modal.type === 'resetDeploy'">
          <p class="modal-text">{{ t('将全部部署配置还原为默认值？') }}{{ t('此操作不可恢复。') }}</p>
          <label class="modal-field">{{ t('模板') }}<AppSelect v-model="modal.template" :options="deployTemplateOptions"/></label>
        </template>
        <p v-else-if="modal.type === 'confirm'" class="modal-text">{{ modalConfirmMessage }}</p>
        <p v-else-if="modal.type === 'alert'" class="modal-text">{{ modalAlertMessage }}</p>
        <p v-else class="modal-text">{{ t('删除') }} {{ modal.name }}？{{ t('此操作不可恢复。') }}</p>
        <div class="modal-actions">
          <button v-if="modal.type !== 'alert'" class="btn" @click="modal.type = ''">{{ t('取消') }}</button>
          <button class="btn" :class="modal.type === 'delete' || modal.type === 'resetDeploy' ? 'danger' : 'primary'" :disabled="modal.busy || (modal.type === 'create' && !modal.name.trim())" @click="confirmModal">{{ modal.type === 'alert' ? t('知道了') : t('确定') }}</button>
        </div>
      </div>
    </div>
  </div>
</template>
