// Canonical brand icon; Windows-native uses (notification, window, Tauri
// build) go through nkas.ico instead, both regenerated by
// dev_tools/replace_project_icons.py.
export const brandIcon = '/static/gui/icon/nkas.png'

export function formatTime(value: string) { const m = String(value || '').match(/^(\d{4})-(\d{2})-(\d{2})\s+(\d{2}:\d{2})/); return m ? `${m[2]}-${m[3]} ${m[4]}` : value }
export function dayOf(value: string) { return String(value || '').slice(0, 10) }
export function formatDate(value: string) { const m = String(value || '').match(/^(\d{4})-(\d{2})-(\d{2})/); return m ? `${m[2]}-${m[3]}` : value }

// Plain text inputs also save on change (blur), so they share the textarea's
// reset problem: any re-render re-applies the stale bound :value and wipes an
// edit that has not blurred yet.  Keep the model in sync on every input so
// re-renders are idempotent.
export function onTextInput(model: { value: any }, event: Event) {
  const input = event.target as HTMLInputElement
  if (model.value !== input.value) model.value = input.value
}
