const { chromium } = require('../webui/node_modules/playwright')
const assert = require('node:assert/strict')

;(async () => {
  const browser = await chromium.launch({ headless: true })
  const page = await browser.newPage({ baseURL: 'http://127.0.0.1:18772' })
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('http://127.0.0.1:18772/app/#/deploy')
  const toggle = page.locator('#deploy-MirrorChyanEnabled')
  await toggle.waitFor()
  async function setEnabled(value) {
    if (await toggle.isChecked() === value) return
    const saved = page.waitForResponse(r => r.url().endsWith('/api/system/deploy') && r.request().method() === 'PATCH')
    await toggle.setChecked(value)
    await saved
  }
  await setEnabled(true)
  const field = page.locator('#mirror-cdk')
  assert.equal(await field.getAttribute('type'), 'password')
  await field.fill('browser-simulation-cdk')
  const saved = page.waitForResponse(r => r.url().endsWith('/api/system/mirror-cdk') && r.request().method() === 'POST')
  await page.locator('.cdk-controls button[type=submit]').click()
  assert.deepEqual(await (await saved).json(), { configured: true })
  await page.waitForFunction(() => document.querySelector('#mirror-cdk').value === '')
  await page.reload()
  await field.waitFor()
  await page.waitForFunction(() => document.querySelector('#mirror-cdk').placeholder === '••••••••')
  assert.equal(await field.inputValue(), '')
  assert.equal(await toggle.isChecked(), true)
  await setEnabled(false)
  assert.deepEqual(await (await page.request.get('/api/system/mirror-cdk')).json(), { configured: true })
  await page.locator('.cdk-controls button[type=button]').click()
  await page.waitForFunction(() => document.querySelector('#mirror-cdk').placeholder !== '••••••••')
  assert.deepEqual(await (await page.request.get('/api/system/mirror-cdk')).json(), { configured: false })
  await setEnabled(true)
  await page.goto('http://127.0.0.1:18772/app/#/settings')
  await page.getByText('更新渠道 · MirrorChyan').waitFor()
  const sourceCard = page.locator('article').filter({ has: page.getByRole('heading', { name: '源码更新', exact: true }) })
  await sourceCard.getByRole('button', { name: '检查更新', exact: true }).click()
  await sourceCard.getByText('有新版本，但 Mirror 酱未返回下载链接', { exact: false }).waitFor()
  assert.equal(await sourceCard.getByRole('button', { name: '立即更新', exact: true }).count(), 0)
  assert.equal(errors.length, 0, errors.join('\n'))
  console.log('MirrorChyan browser simulations passed: switch, masked CDK save/clear, persisted state and missing-URL error')
  await browser.close()
})().catch(error => { console.error(error); process.exit(1) })
