from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

COOP_ACCEPT = Button(area={'cn': (501, 842, 550, 867)}, color={'cn': (112, 197, 236)}, button={'cn': (501, 842, 550, 867)}, file={'cn': './assets/cn/coop/COOP_ACCEPT.png'})
COOP_CHECK = Button(area={'cn': (458, 182, 608, 205)}, color={'cn': (75, 75, 73)}, button={'cn': (458, 182, 608, 205)}, file={'cn': './assets/cn/coop/COOP_CHECK.png'})
COOP_PREPARE = Button(area={'cn': (334, 1195, 386, 1220)}, color={'cn': (148, 199, 249)}, button={'cn': (334, 1195, 386, 1220)}, file={'cn': './assets/cn/coop/COOP_PREPARE.png'})
COOP_START = Button(area={'cn': (477, 979, 587, 1005)}, color={'cn': (250, 149, 136)}, button={'cn': (477, 979, 587, 1005)}, file={'cn': './assets/cn/coop/COOP_START.png'})
DATELINE_CHECK = Button(area={'cn': (569, 285, 628, 304)}, color={'cn': (131, 93, 23)}, button={'cn': (569, 285, 628, 304)}, file={'cn': './assets/cn/coop/DATELINE_CHECK.png'})
FREE_OPPORTUNITY_CHECK = Button(area={'cn': (568, 1012, 584, 1030)}, color={'cn': (251, 108, 93)}, button={'cn': (568, 1012, 584, 1030)}, file={'cn': './assets/cn/coop/FREE_OPPORTUNITY_CHECK.png'})
FREE_OPPORTUNITY_CHECK1 = Button(area={'cn': (570, 1014, 604, 1027)}, color={'cn': (250, 139, 125)}, button={'cn': (570, 1014, 604, 1027)}, file={'cn': './assets/cn/coop/FREE_OPPORTUNITY_CHECK1.png'})
