# ==================== NKAS ====================

Restart:
  Scheduler:
    Enable:
      value: true
      display: disabled

# ==================== Reward ====================

Reward:
  Scheduler:
    Enable:
      value: true
      type: lock
