# ==================== NKAS ====================

NKAS:
  - Emulator
  - Optimization
  - Notification

Restart:
  - Scheduler

# ==================== Reward ====================

Reward:
  - Scheduler
  - Reward

Destruction:
  - Scheduler

Commission:
  - Scheduler
  - CollectionItems

Mailbox:
  - Scheduler

# ==================== Daily ====================
Blablalink:
  - Scheduler
  - BlaAuth
  - BlaDaily
  - CDK

DailyRecruit:
  - Scheduler
  - DailyRecruit

Daily:
  - Scheduler
  - Daily

MissionPass:
  - Scheduler

Liberation:
  - Scheduler

Conversation:
  - Scheduler
  - Conversation

Shop:
  - Scheduler
  - GeneralShop
  - ArenaShop

RubbishShop:
  - Scheduler
  - RubbishShop

SimulationRoom:
  - Scheduler
  - Area

TribeTower:
  - Scheduler
  - Overcome

RookieArena:
  - Scheduler
  - OpponentSelection

SpecialArena:
  - Scheduler
  - OpponentSelection

Interception:
  - Scheduler

StoryEvent:
  - Scheduler
  - StoryEvent

# ==================== Tools ====================

TowerDaemon:
  - Scheduler

CombatDaemon:
  - Scheduler

EventDaemon:
  - Scheduler

# ==================== Gift ====================

DailyGift:
  - Scheduler

WeeklyGift:
  - Scheduler

MonthlyGift:
  - Scheduler