from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/event_button_extract.py.
# Don't modify it manually.

COOP_ENTER = Button(area={'cn': (324, 1165, 396, 1184)}, color={'cn': (143, 173, 220)}, button={'cn': (324, 1165, 396, 1184)}, file={'cn': './assets/story_event/event_20250612/COOP_ENTER.png'})
COOP_SELECT_CHECK = Button(area={'cn': (307, 623, 441, 655)}, color={'cn': (102, 102, 101)}, button={'cn': (307, 623, 441, 655)}, file={'cn': './assets/story_event/event_20250612/COOP_SELECT_CHECK.png'})
EVENT_CHECK = Button(area={'cn': (20, 37, 91, 54)}, color={'cn': (145, 143, 140)}, button={'cn': (20, 37, 91, 54)}, file={'cn': './assets/story_event/event_20250612/EVENT_CHECK.png'})
EVENT_GOTO_STORY_1 = Button(area={'cn': (126, 951, 231, 967)}, color={'cn': (102, 133, 186)}, button={'cn': (126, 951, 231, 967)}, file={'cn': './assets/story_event/event_20250612/EVENT_GOTO_STORY_1.png'})
EVENT_GOTO_STORY_2 = Button(area={'cn': (114, 1026, 194, 1044)}, color={'cn': (109, 141, 195)}, button={'cn': (114, 1026, 194, 1044)}, file={'cn': './assets/story_event/event_20250612/EVENT_GOTO_STORY_2.png'})
LOGIN_STAMP = Button(area={'cn': (518, 1025, 592, 1044)}, color={'cn': (138, 166, 211)}, button={'cn': (518, 1025, 592, 1044)}, file={'cn': './assets/story_event/event_20250612/LOGIN_STAMP.png'})
LOGIN_STAMP_CHECK = Button(area={'cn': (341, 133, 607, 189)}, color={'cn': (127, 169, 205)}, button={'cn': (341, 133, 607, 189)}, file={'cn': './assets/story_event/event_20250612/LOGIN_STAMP_CHECK.png'})
LOGIN_STAMP_DONE = Button(area={'cn': (488, 1188, 609, 1213)}, color={'cn': (65, 67, 66)}, button={'cn': (488, 1188, 609, 1213)}, file={'cn': './assets/story_event/event_20250612/LOGIN_STAMP_DONE.png'})
LOGIN_STAMP_RECEIVE = Button(area={'cn': (297, 811, 423, 832)}, color={'cn': (58, 59, 61)}, button={'cn': (297, 811, 423, 832)}, file={'cn': './assets/story_event/event_20250612/LOGIN_STAMP_RECEIVE.png'})
LOGIN_STAMP_REWARD = Button(area={'cn': (489, 1189, 611, 1213)}, color={'cn': (153, 165, 171)}, button={'cn': (489, 1189, 611, 1213)}, file={'cn': './assets/story_event/event_20250612/LOGIN_STAMP_REWARD.png'})
MAIN_GOTO_EVENT = Button(area={'cn': (476, 1066, 559, 1099)}, color={'cn': (144, 154, 181)}, button={'cn': (476, 1066, 559, 1099)}, file={'cn': './assets/story_event/event_20250612/MAIN_GOTO_EVENT.png'})
SKIP = Button(area={'cn': (616, 22, 671, 41)}, color={'cn': (133, 134, 133)}, button={'cn': (616, 22, 671, 41)}, file={'cn': './assets/story_event/event_20250612/SKIP.png'})
STORY_1_CHECK = Button(area={'cn': (19, 38, 91, 56)}, color={'cn': (146, 146, 144)}, button={'cn': (19, 38, 91, 56)}, file={'cn': './assets/story_event/event_20250612/STORY_1_CHECK.png'})
STORY_2_CHECK = Button(area={'cn': (408, 913, 549, 963)}, color={'cn': (201, 158, 119)}, button={'cn': (408, 913, 549, 963)}, file={'cn': './assets/story_event/event_20250612/STORY_2_CHECK.png'})
TEMPLATE_COOP_ENABLE = Template(file={'cn': './assets/story_event/event_20250612/TEMPLATE_COOP_ENABLE.png'})
