from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

FAVORITE_ITEM_BAY_ICON = Button(area={'zh-CN': (0, 0, 256, 256), 'en-US': (0, 0, 256, 256)}, color={'zh-CN': (156, 177, 192), 'en-US': (156, 177, 192)}, button={'zh-CN': (0, 0, 256, 256), 'en-US': (0, 0, 256, 256)}, file={'zh-CN': './assets/zh-CN/warehouse_stats/FAVORITE_ITEM_BAY_ICON.png', 'en-US': './assets/zh-CN/warehouse_stats/FAVORITE_ITEM_BAY_ICON.png'})
FAVORITE_ITEM_BAY_TEMPLATE = Button(area={'zh-CN': (0, 0, 256, 256), 'en-US': (0, 0, 256, 256)}, color={'zh-CN': (156, 177, 192), 'en-US': (156, 177, 192)}, button={'zh-CN': (0, 0, 256, 256), 'en-US': (0, 0, 256, 256)}, file={'zh-CN': './assets/zh-CN/warehouse_stats/FAVORITE_ITEM_BAY_TEMPLATE.png', 'en-US': './assets/zh-CN/warehouse_stats/FAVORITE_ITEM_BAY_TEMPLATE.png'})
FAVORITE_ITEM_CENTI_ICON = Button(area={'zh-CN': (0, 0, 88, 89), 'en-US': (0, 0, 88, 89)}, color={'zh-CN': (181, 186, 191), 'en-US': (181, 186, 191)}, button={'zh-CN': (0, 0, 88, 89), 'en-US': (0, 0, 88, 89)}, file={'zh-CN': './assets/zh-CN/warehouse_stats/FAVORITE_ITEM_CENTI_ICON.png', 'en-US': './assets/zh-CN/warehouse_stats/FAVORITE_ITEM_CENTI_ICON.png'})
FAVORITE_ITEM_CENTI_TEMPLATE = Button(area={'zh-CN': (0, 0, 88, 89), 'en-US': (0, 0, 88, 89)}, color={'zh-CN': (181, 186, 191), 'en-US': (181, 186, 191)}, button={'zh-CN': (0, 0, 88, 89), 'en-US': (0, 0, 88, 89)}, file={'zh-CN': './assets/zh-CN/warehouse_stats/FAVORITE_ITEM_CENTI_TEMPLATE.png', 'en-US': './assets/zh-CN/warehouse_stats/FAVORITE_ITEM_CENTI_TEMPLATE.png'})
FAVORITE_ITEM_ZWEI_ICON = Button(area={'zh-CN': (0, 0, 91, 92), 'en-US': (0, 0, 91, 92)}, color={'zh-CN': (174, 155, 132), 'en-US': (174, 155, 132)}, button={'zh-CN': (0, 0, 91, 92), 'en-US': (0, 0, 91, 92)}, file={'zh-CN': './assets/zh-CN/warehouse_stats/FAVORITE_ITEM_ZWEI_ICON.png', 'en-US': './assets/zh-CN/warehouse_stats/FAVORITE_ITEM_ZWEI_ICON.png'})
FAVORITE_ITEM_ZWEI_TEMPLATE = Button(area={'zh-CN': (0, 0, 91, 92), 'en-US': (0, 0, 91, 92)}, color={'zh-CN': (174, 155, 132), 'en-US': (174, 155, 132)}, button={'zh-CN': (0, 0, 91, 92), 'en-US': (0, 0, 91, 92)}, file={'zh-CN': './assets/zh-CN/warehouse_stats/FAVORITE_ITEM_ZWEI_TEMPLATE.png', 'en-US': './assets/zh-CN/warehouse_stats/FAVORITE_ITEM_ZWEI_TEMPLATE.png'})
