from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

MINI_GAME = Button(area={'zh-cn': (551, 961, 604, 978)}, color={'zh-cn': (148, 149, 168)}, button={'zh-cn': (551, 961, 604, 978)}, file={'zh-cn': './assets/zh-cn/event_minigame/event_20250716/MINI_GAME.png'})
MINI_GAME_BACK = Button(area={'zh-cn': (334, 1093, 385, 1117)}, color={'zh-cn': (153, 127, 88)}, button={'zh-cn': (334, 1093, 385, 1117)}, file={'zh-cn': './assets/zh-cn/event_minigame/event_20250716/MINI_GAME_BACK.png'})
MINI_GAME_BACK_CONFIRM = Button(area={'zh-cn': (507, 789, 555, 812)}, color={'zh-cn': (109, 196, 236)}, button={'zh-cn': (507, 789, 555, 812)}, file={'zh-cn': './assets/zh-cn/event_minigame/event_20250716/MINI_GAME_BACK_CONFIRM.png'})
MINI_GAME_CHECK = Button(area={'zh-cn': (260, 1070, 297, 1123)}, color={'zh-cn': (241, 163, 124)}, button={'zh-cn': (260, 1070, 297, 1123)}, file={'zh-cn': './assets/zh-cn/event_minigame/event_20250716/MINI_GAME_CHECK.png'})
MINI_GAME_CLOSE = Button(area={'zh-cn': (606, 373, 641, 409)}, color={'zh-cn': (149, 150, 139)}, button={'zh-cn': (606, 373, 641, 409)}, file={'zh-cn': './assets/zh-cn/event_minigame/event_20250716/MINI_GAME_CLOSE.png'})
MINI_GAME_EXEC_CHECK = Button(area={'zh-cn': (605, 39, 642, 73)}, color={'zh-cn': (146, 136, 126)}, button={'zh-cn': (605, 39, 642, 73)}, file={'zh-cn': './assets/zh-cn/event_minigame/event_20250716/MINI_GAME_EXEC_CHECK.png'})
MINI_GAME_MISSION = Button(area={'zh-cn': (267, 390, 296, 420)}, color={'zh-cn': (151, 116, 49)}, button={'zh-cn': (267, 390, 296, 420)}, file={'zh-cn': './assets/zh-cn/event_minigame/event_20250716/MINI_GAME_MISSION.png'})
MINI_GAME_MISSION_CHECK = Button(area={'zh-cn': (330, 138, 388, 167)}, color={'zh-cn': (158, 158, 148)}, button={'zh-cn': (330, 138, 388, 167)}, file={'zh-cn': './assets/zh-cn/event_minigame/event_20250716/MINI_GAME_MISSION_CHECK.png'})
MINI_GAME_MISSION_CLOSE = Button(area={'zh-cn': (609, 134, 646, 170)}, color={'zh-cn': (147, 147, 137)}, button={'zh-cn': (609, 134, 646, 170)}, file={'zh-cn': './assets/zh-cn/event_minigame/event_20250716/MINI_GAME_MISSION_CLOSE.png'})
MINI_GAME_MISSION_DONE = Button(area={'zh-cn': (301, 1122, 418, 1141)}, color={'zh-cn': (143, 143, 143)}, button={'zh-cn': (301, 1122, 418, 1141)}, file={'zh-cn': './assets/zh-cn/event_minigame/event_20250716/MINI_GAME_MISSION_DONE.png'})
MINI_GAME_MISSION_REWARD = Button(area={'zh-cn': (309, 1119, 410, 1143)}, color={'zh-cn': (161, 133, 77)}, button={'zh-cn': (309, 1119, 410, 1143)}, file={'zh-cn': './assets/zh-cn/event_minigame/event_20250716/MINI_GAME_MISSION_REWARD.png'})
MINI_GAME_REWARD = Button(area={'zh-cn': (306, 732, 413, 751)}, color={'zh-cn': (171, 137, 59)}, button={'zh-cn': (306, 732, 413, 751)}, file={'zh-cn': './assets/zh-cn/event_minigame/event_20250716/MINI_GAME_REWARD.png'})
MINI_GAME_REWARD_DONE = Button(area={'zh-cn': (145, 669, 198, 688)}, color={'zh-cn': (113, 128, 137)}, button={'zh-cn': (145, 669, 198, 688)}, file={'zh-cn': './assets/zh-cn/event_minigame/event_20250716/MINI_GAME_REWARD_DONE.png'})
MINI_GAME_SKILL1 = Button(area={'zh-cn': (42, 170, 76, 212)}, color={'zh-cn': (97, 114, 224)}, button={'zh-cn': (42, 170, 76, 212)}, file={'zh-cn': './assets/zh-cn/event_minigame/event_20250716/MINI_GAME_SKILL1.png'})
MINI_GAME_SKILL2 = Button(area={'zh-cn': (144, 167, 174, 212)}, color={'zh-cn': (166, 176, 236)}, button={'zh-cn': (144, 167, 174, 212)}, file={'zh-cn': './assets/zh-cn/event_minigame/event_20250716/MINI_GAME_SKILL2.png'})
MINI_GAME_START = Button(area={'zh-cn': (260, 1070, 297, 1123)}, color={'zh-cn': (241, 163, 124)}, button={'zh-cn': (260, 1070, 297, 1123)}, file={'zh-cn': './assets/zh-cn/event_minigame/event_20250716/MINI_GAME_START.png'})
MINI_GAME_TIME_OUT = Button(area={'zh-cn': (310, 162, 354, 189)}, color={'zh-cn': (156, 155, 142)}, button={'zh-cn': (310, 162, 354, 189)}, file={'zh-cn': './assets/zh-cn/event_minigame/event_20250716/MINI_GAME_TIME_OUT.png'})
MINI_GAME_TOUCH = Button(area={'zh-cn': (368, 795, 526, 824)}, color={'zh-cn': (122, 89, 89)}, button={'zh-cn': (368, 795, 526, 824)}, file={'zh-cn': './assets/zh-cn/event_minigame/event_20250716/MINI_GAME_TOUCH.png'})
