from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

CLAIM = Button(area={'zh-cn': (487, 1060, 516, 1090)}, color={'zh-cn': (73, 197, 255)}, button={'zh-cn': (487, 1060, 516, 1090)}, file={'zh-cn': './assets/zh-cn/commission/CLAIM.png'})
CLAIM_DONE = Button(area={'zh-cn': (209, 692, 370, 716)}, color={'zh-cn': (186, 186, 186)}, button={'zh-cn': (209, 692, 370, 716)}, file={'zh-cn': './assets/zh-cn/commission/CLAIM_DONE.png'})
DIESEL = Button(area={'zh-cn': (114, 614, 147, 634)}, color={'zh-cn': (162, 105, 75)}, button={'zh-cn': (114, 614, 147, 634)}, file={'zh-cn': './assets/zh-cn/commission/DIESEL.png'})
DISPATCH = Button(area={'zh-cn': (290, 1066, 425, 1086)}, color={'zh-cn': (120, 212, 252)}, button={'zh-cn': (290, 1066, 425, 1086)}, file={'zh-cn': './assets/zh-cn/commission/DISPATCH.png'})
DISPATCH_CONFIRM = Button(area={'zh-cn': (383, 1058, 504, 1095)}, color={'zh-cn': (70, 196, 255)}, button={'zh-cn': (383, 1058, 504, 1095)}, file={'zh-cn': './assets/zh-cn/commission/DISPATCH_CONFIRM.png'})
DRAKE = Button(area={'zh-cn': (93, 656, 135, 678)}, color={'zh-cn': (183, 155, 168)}, button={'zh-cn': (93, 656, 135, 678)}, file={'zh-cn': './assets/zh-cn/commission/DRAKE.png'})
EXIA = Button(area={'zh-cn': (113, 698, 133, 722)}, color={'zh-cn': (144, 104, 75)}, button={'zh-cn': (113, 698, 133, 722)}, file={'zh-cn': './assets/zh-cn/commission/EXIA.png'})
FRIMA = Button(area={'zh-cn': (106, 820, 135, 844)}, color={'zh-cn': (84, 66, 75)}, button={'zh-cn': (106, 820, 135, 844)}, file={'zh-cn': './assets/zh-cn/commission/FRIMA.png'})
HELM = Button(area={'zh-cn': (102, 436, 122, 457)}, color={'zh-cn': (130, 140, 156)}, button={'zh-cn': (102, 436, 122, 457)}, file={'zh-cn': './assets/zh-cn/commission/HELM.png'})
ITEM_LIST_CHECK = Button(area={'zh-cn': (283, 172, 303, 198)}, color={'zh-cn': (116, 171, 229)}, button={'zh-cn': (283, 172, 303, 198)}, file={'zh-cn': './assets/zh-cn/commission/ITEM_LIST_CHECK.png'})
ITEM_LIST_SELECTED = Button(area={'zh-cn': (527, 754, 549, 797)}, color={'zh-cn': (230, 250, 255)}, button={'zh-cn': (527, 754, 549, 797)}, file={'zh-cn': './assets/zh-cn/commission/ITEM_LIST_SELECTED.png'})
ITEM_LIST_SELECT_CONFIRM = Button(area={'zh-cn': (386, 1071, 414, 1089)}, color={'zh-cn': (179, 230, 255)}, button={'zh-cn': (386, 1071, 414, 1089)}, file={'zh-cn': './assets/zh-cn/commission/ITEM_LIST_SELECT_CONFIRM.png'})
ITEM_SELECTED = Button(area={'zh-cn': (64, 429, 82, 436)}, color={'zh-cn': (214, 99, 50)}, button={'zh-cn': (64, 429, 82, 436)}, file={'zh-cn': './assets/zh-cn/commission/ITEM_SELECTED.png'})
ITEM_SELECTED_NUM = Button(area={'zh-cn': (271, 557, 449, 588)}, color={'zh-cn': (227, 228, 227)}, button={'zh-cn': (271, 557, 449, 588)}, file={'zh-cn': './assets/zh-cn/commission/ITEM_SELECTED_NUM.png'})
ITEM_SELECTED_NUM_CHECK = Button(area={'zh-cn': (336, 304, 378, 342)}, color={'zh-cn': (238, 158, 66)}, button={'zh-cn': (336, 304, 378, 342)}, file={'zh-cn': './assets/zh-cn/commission/ITEM_SELECTED_NUM_CHECK.png'})
LAPLACE = Button(area={'zh-cn': (107, 932, 135, 951)}, color={'zh-cn': (54, 90, 177)}, button={'zh-cn': (107, 932, 135, 951)}, file={'zh-cn': './assets/zh-cn/commission/LAPLACE.png'})
MILK = Button(area={'zh-cn': (105, 847, 136, 876)}, color={'zh-cn': (212, 158, 180)}, button={'zh-cn': (105, 847, 136, 876)}, file={'zh-cn': './assets/zh-cn/commission/MILK.png'})
POLI = Button(area={'zh-cn': (107, 654, 142, 684)}, color={'zh-cn': (158, 148, 121)}, button={'zh-cn': (107, 654, 142, 684)}, file={'zh-cn': './assets/zh-cn/commission/POLI.png'})
SELECT = Button(area={'zh-cn': (387, 457, 410, 480)}, color={'zh-cn': (59, 192, 255)}, button={'zh-cn': (387, 457, 410, 480)}, file={'zh-cn': './assets/zh-cn/commission/SELECT.png'})
TOVE = Button(area={'zh-cn': (104, 863, 154, 897)}, color={'zh-cn': (106, 94, 73)}, button={'zh-cn': (104, 863, 154, 897)}, file={'zh-cn': './assets/zh-cn/commission/TOVE.png'})
VIPER = Button(area={'zh-cn': (130, 400, 158, 424)}, color={'zh-cn': (71, 71, 70)}, button={'zh-cn': (130, 400, 158, 424)}, file={'zh-cn': './assets/zh-cn/commission/VIPER.png'})
